//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 212.150301 on Stable branch
// Generated with ALiVE version 1.19.0.2301051
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_VDURF {
        displayName = "Viridian Dawn";
        side = 0;
        flag = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        icon = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_VDURF {
            name = "Viridian Dawn";

            class Infantry {
                name = "Infantry";

                class o_ovdurf_infantry_insurgent_squad {
                    name = "Insurgent Squad";
                    side = 0;
                    faction = "O_VDURF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OVDURF_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Autorifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Autorifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Marksman_01";
                    };
                };

                class o_ovdurf_infantry_insurgent_fireteam {
                    name = "Insurgent Fireteam";
                    side = 0;
                    faction = "O_VDURF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OVDURF_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OVDURF_Rifleman_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class OPTRE_Ins_ER_Unarmed_IND;
    class OPTRE_Ins_ER_Unarmed_IND_OCimport_01 : OPTRE_Ins_ER_Unarmed_IND { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Unarmed_IND_OCimport_02 : OPTRE_Ins_ER_Unarmed_IND_OCimport_01 { class EventHandlers; };


    class O_OVDURF_Rifleman_01 : OPTRE_Ins_ER_Unarmed_IND_OCimport_02 {
        author = "Sgt. J. Flowers";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_VDURF";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "U_I_C_Soldier_Para_4_F";

        linkedItems[] = {"V_TacChestrig_grn_F","H_MilCap_grn","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_TacChestrig_grn_F","H_MilCap_grn","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"LM_OPCAN_CTAR"};
        respawnWeapons[] = {"LM_OPCAN_CTAR"};

        magazines[] = {"30Rnd_580x42_Mag_F","30Rnd_580x42_Mag_F"};
        respawnMagazines[] = {"30Rnd_580x42_Mag_F","30Rnd_580x42_Mag_F"};

        ALiVE_orbatCreator_loadout[] = {{"LM_OPCAN_CTAR","","","OPTRE_M7_Sight",{"30Rnd_580x42_Mag_F",30},{},""},{},{},{"U_I_C_Soldier_Para_4_F",{{"ACE_elasticBandage",5},{"ACE_packingBandage",3},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_MRE_BeefStew",1},{"ACE_tourniquet",2}}},{"V_TacChestrig_grn_F",{{"OPTRE_M9_Frag",1,1},{"30Rnd_580x42_Mag_F",8,30}}},{},"H_MilCap_grn","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OVDURF_Marksman_01 : O_OVDURF_Rifleman_01 {
        author = "Sgt. J. Flowers";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "O_VDURF";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "U_I_C_Soldier_Para_4_F";

        linkedItems[] = {"V_TacChestrig_grn_F","H_Watchcap_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_TacChestrig_grn_F","H_Watchcap_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"LM_OPCAN_DMR0M37"};
        respawnWeapons[] = {"LM_OPCAN_DMR0M37"};

        magazines[] = {"ACE_30Rnd_65_Creedmor_msbs_mag","ACE_30Rnd_65_Creedmor_msbs_mag"};
        respawnMagazines[] = {"ACE_30Rnd_65_Creedmor_msbs_mag","ACE_30Rnd_65_Creedmor_msbs_mag"};

        ALiVE_orbatCreator_loadout[] = {{"LM_OPCAN_DMR0M37","","","optic_Arco_blk_F",{"ACE_30Rnd_65_Creedmor_msbs_mag",30},{},""},{},{},{"U_I_C_Soldier_Para_4_F",{{"ACE_elasticBandage",5},{"ACE_packingBandage",3},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_MRE_BeefStew",1},{"ACE_tourniquet",2}}},{"V_TacChestrig_grn_F",{{"OPTRE_M9_Frag",1,1},{"ACE_30Rnd_65_Creedmor_msbs_mag",9,30}}},{},"H_Watchcap_blk","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OVDURF_Grenadier_01 : O_OVDURF_Rifleman_01 {
        author = "Sgt. J. Flowers";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "O_VDURF";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "U_I_C_Soldier_Para_4_F";

        linkedItems[] = {"V_TacChestrig_grn_F","H_MilCap_grn","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_TacChestrig_grn_F","H_MilCap_grn","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"LM_OPCAN_CTAR_GL"};
        respawnWeapons[] = {"LM_OPCAN_CTAR_GL"};

        magazines[] = {"30Rnd_580x42_Mag_F","30Rnd_580x42_Mag_F"};
        respawnMagazines[] = {"30Rnd_580x42_Mag_F","30Rnd_580x42_Mag_F"};

        ALiVE_orbatCreator_loadout[] = {{"LM_OPCAN_CTAR_GL","","","OPTRE_M7_Sight",{"30Rnd_580x42_Mag_F",30},{},""},{},{},{"U_I_C_Soldier_Para_4_F",{{"ACE_elasticBandage",5},{"ACE_packingBandage",3},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_MRE_BeefStew",1},{"ACE_tourniquet",2},{"30Rnd_580x42_Mag_F",2,30}}},{"V_TacChestrig_grn_F",{{"OPTRE_M9_Frag",1,1},{"30Rnd_580x42_Mag_F",8,30},{"1Rnd_HE_Grenade_shell",3,1}}},{},"H_MilCap_grn","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OVDURF_Autorifleman_01 : O_OVDURF_Rifleman_01 {
        author = "Sgt. J. Flowers";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 0;
        faction = "O_VDURF";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "U_I_C_Soldier_Para_4_F";

        linkedItems[] = {"V_TacChestrig_grn_F","H_Booniehat_mgrn","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_TacChestrig_grn_F","H_Booniehat_mgrn","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"LM_OPCAN_CTAR_SAW"};
        respawnWeapons[] = {"LM_OPCAN_CTAR_SAW"};

        magazines[] = {"100Rnd_580x42_Mag_F","100Rnd_580x42_Mag_F"};
        respawnMagazines[] = {"100Rnd_580x42_Mag_F","100Rnd_580x42_Mag_F"};

        backpack = "B_FieldPack_oli";

        ALiVE_orbatCreator_loadout[] = {{"LM_OPCAN_CTAR_SAW","","","OPTRE_M7_Sight",{"100Rnd_580x42_Mag_F",100},{},""},{},{},{"U_I_C_Soldier_Para_4_F",{{"ACE_elasticBandage",5},{"ACE_packingBandage",3},{"ACE_CableTie",2},{"ACE_epinephrine",2},{"ACE_morphine",2},{"ACE_MRE_BeefStew",1},{"ACE_tourniquet",2}}},{"V_TacChestrig_grn_F",{{"OPTRE_M9_Frag",1,1},{"30Rnd_580x42_Mag_F",8,30}}},{"B_FieldPack_oli",{{"100Rnd_580x42_Mag_F",8,100}}},"H_Booniehat_mgrn","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};