//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_NFM {
        displayName = "New Friden Movement";
        side = 0;
        flag = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        icon = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_NFM {
            name = "New Friden Movement";

            class Infantry {
                name = "Infantry";

                class o_nfm_infantry_fireteam {
                    name = "Fireteam";
                    side = 0;
                    faction = "o_nfm";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_NFM_Team_Leader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_NFM_Autorifleman";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Grenadier";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Rifleman";
                    };
                };

                class o_nfm_infantry_patrol {
                    name = "Patrol";
                    side = 0;
                    faction = "o_nfm";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_NFM_Patrol";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_NFM_Patrol";
                    };
                };

                class o_nfm_infantry_squad {
                    name = "Squad";
                    side = 0;
                    faction = "o_nfm";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_NFM_Squad_Leader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_NFM_Team_Leader";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Autorifleman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Marksman";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Rifleman";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_NFM_Team_Leader";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Autorifleman";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Grenadier";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Rifleman";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_NFM_Team_Leader";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Grenadier";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Marksman";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Rifleman";
                    };
                };

                class o_nfm_infantry_anti_armor_team {
                    name = "Anti Armor Team";
                    side = 0;
                    faction = "o_nfm";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_NFM_Team_Leader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_NFM_Autorifleman";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Anti_Tank";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Anti_Tank";
                    };
                };

                class o_nfm_infantry_anti_air_team {
                    name = "Anti Air Team";
                    side = 0;
                    faction = "o_nfm";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_NFM_Team_Leader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_NFM_Marksman";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Anti_Air";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Anti_Air";
                    };
                };

                class o_nfm_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 0;
                    faction = "o_nfm";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_NFM_Sniper";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_NFM_Sniper";
                    };
                };

                class o_nfm_infantry_command_team {
                    name = "Command Team";
                    side = 0;
                    faction = "o_nfm";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_NFM_Officer";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_NFM_Team_Leader";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_NFM_Autorifleman";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Marksman";
                    };
                    class Unit4 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Grenadier";
                    };
                };

                class o_nfm_infantry_medical_team {
                    name = "Medical Team";
                    side = 0;
                    faction = "o_nfm";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_NFM_Squad_Leader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_NFM_Autorifleman";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Medic";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_NFM_Medic";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LM_OPCAN_FRI_Rifleman_WDL;
    class LM_OPCAN_FRI_Rifleman_WDL_OCimport_01 : LM_OPCAN_FRI_Rifleman_WDL { scope = 0; class EventHandlers; };
    class LM_OPCAN_FRI_Rifleman_WDL_OCimport_02 : LM_OPCAN_FRI_Rifleman_WDL_OCimport_01 { class EventHandlers; };

    class OPTRE_UNSC_hornet_CAS;
    class OPTRE_UNSC_hornet_CAS_OCimport_01 : OPTRE_UNSC_hornet_CAS { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_UNSC_hornet_CAS_OCimport_02 : OPTRE_UNSC_hornet_CAS_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class OPTRE_M412_IFV_UNSC;
    class OPTRE_M412_IFV_UNSC_OCimport_01 : OPTRE_M412_IFV_UNSC { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M412_IFV_UNSC_OCimport_02 : OPTRE_M412_IFV_UNSC_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_M12_LRV;
    class OPTRE_M12_LRV_OCimport_01 : OPTRE_M12_LRV { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_LRV_OCimport_02 : OPTRE_M12_LRV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M12R_AA;
    class OPTRE_M12R_AA_OCimport_01 : OPTRE_M12R_AA { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12R_AA_OCimport_02 : OPTRE_M12R_AA_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M12A1_LRV;
    class OPTRE_M12A1_LRV_OCimport_01 : OPTRE_M12A1_LRV { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12A1_LRV_OCimport_02 : OPTRE_M12A1_LRV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M12_FAV_APC;
    class OPTRE_M12_FAV_APC_OCimport_01 : OPTRE_M12_FAV_APC { scope = 0; class EventHandlers; };
    class OPTRE_M12_FAV_APC_OCimport_02 : OPTRE_M12_FAV_APC_OCimport_01 { scope = 0; class EventHandlers; };

    class OPTRE_M813_TT;
    class OPTRE_M813_TT_OCimport_01 : OPTRE_M813_TT { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M813_TT_OCimport_02 : OPTRE_M813_TT_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoGunner_02;
            class CargoGunner_03;
            class CargoGunner_04;
            class CargoGunner_05;
            class CargoGunner_06;
            class CargoGunner_07;
        };
    };

    class OPTRE_M808B_UNSC;
    class OPTRE_M808B_UNSC_OCimport_01 : OPTRE_M808B_UNSC { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M808B_UNSC_OCimport_02 : OPTRE_M808B_UNSC_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret1;
            class CargoTurret2;
            class CargoTurret3;
            class CargoTurret4;
            class CargoTurret5;
            class CargoTurret6;
            class CargoTurret7;
            class CargoTurret8;
        };
    };

    class OPTRE_Pelican_armed;
    class OPTRE_Pelican_armed_OCimport_01 : OPTRE_Pelican_armed { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Pelican_armed_OCimport_02 : OPTRE_Pelican_armed_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class OPTRE_m1015_mule_mlr_ins_IND;
    class OPTRE_m1015_mule_mlr_ins_IND_OCimport_01 : OPTRE_m1015_mule_mlr_ins_IND { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_m1015_mule_mlr_ins_IND_OCimport_02 : OPTRE_m1015_mule_mlr_ins_IND_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_AU_44_INS_Mortar;
    class OPTRE_AU_44_INS_Mortar_OCimport_01 : OPTRE_AU_44_INS_Mortar { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_AU_44_INS_Mortar_OCimport_02 : OPTRE_AU_44_INS_Mortar_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_LAU65D_pod;
    class OPTRE_LAU65D_pod_OCimport_01 : OPTRE_LAU65D_pod { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_LAU65D_pod_OCimport_02 : OPTRE_LAU65D_pod_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_M494;
    class OPTRE_M494_OCimport_01 : OPTRE_M494 { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M494_OCimport_02 : OPTRE_M494_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_Static_AA;
    class OPTRE_Static_AA_OCimport_01 : OPTRE_Static_AA { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Static_AA_OCimport_02 : OPTRE_Static_AA_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_Static_FG75_IND;
    class OPTRE_Static_FG75_IND_OCimport_01 : OPTRE_Static_FG75_IND { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Static_FG75_IND_OCimport_02 : OPTRE_Static_FG75_IND_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class optre_catfish_mg_f;
    class optre_catfish_mg_f_OCimport_01 : optre_catfish_mg_f { scope = 0; class EventHandlers; class Turrets; };
    class optre_catfish_mg_f_OCimport_02 : optre_catfish_mg_f_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class MainTurret;
        };
    };

    class optre_catfish_unarmed_f;
    class optre_catfish_unarmed_f_OCimport_01 : optre_catfish_unarmed_f { scope = 0; class EventHandlers; class Turrets; };
    class optre_catfish_unarmed_f_OCimport_02 : optre_catfish_unarmed_f_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
        };
    };

    class OPTRE_UNSC_falcon_armed_S;
    class OPTRE_UNSC_falcon_armed_S_OCimport_01 : OPTRE_UNSC_falcon_armed_S { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_UNSC_falcon_armed_S_OCimport_02 : OPTRE_UNSC_falcon_armed_S_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class LeftDoorGun;
            class RightDoorGun;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
        };
    };

    class OPTRE_Static_M41;
    class OPTRE_Static_M41_OCimport_01 : OPTRE_Static_M41 { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Static_M41_OCimport_02 : OPTRE_Static_M41_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_Static_ATGM;
    class OPTRE_Static_ATGM_OCimport_01 : OPTRE_Static_ATGM { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Static_ATGM_OCimport_02 : OPTRE_Static_ATGM_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };


    class O_NFM_Rifleman : LM_OPCAN_FRI_Rifleman_WDL_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Vest","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_FRI_Vest","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"TCF_ARM37","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"TCF_ARM37","TCF_M6B_Wood","Binocular"};

        magazines[] = {"TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARM37","","","TCF_SENT_CG",{"TCF_32Rnd_762x51_Mag_APT",32},{},""},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Vest",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",1},{"TCF_32Rnd_762x51_Mag_APT",8,32}}},{},"TCF_Frihelm_W","TCF_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Marksman : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Vest","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_FRI_Vest","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"TCF_ARM37_DMR","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"TCF_ARM37_DMR","TCF_M6B_Wood","Binocular"};

        magazines[] = {"TCF_15Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag","TCF_15Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"TCF_15Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag","TCF_15Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARM37_DMR","","","OPTRE_M392_Scope",{"TCF_15Rnd_762x51_Mag_APT",15},{},"bipod_01_F_blk"},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Vest",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",2},{"TCF_15Rnd_762x51_Mag_APT",10,15}}},{},"TCF_Frihelm_W","TCF_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Grenadier : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Vest","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_FRI_Vest","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"TCF_ARM37_GL","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"TCF_ARM37_GL","TCF_M6B_Wood","Binocular"};

        magazines[] = {"TCF_32Rnd_762x51_Mag_APT","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"TCF_32Rnd_762x51_Mag_APT","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_AP_Mag"};

        backpack = "TCF_RUCKSACK_UNSC_WDL_F";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARM37_GL","","","TCF_SENT_CG",{"TCF_32Rnd_762x51_Mag_APT",32},{"1Rnd_HE_Grenade_shell",1},""},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Vest",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",3},{"TCF_32Rnd_762x51_Mag_APT",8,32}}},{"TCF_RUCKSACK_UNSC_WDL_F",{{"1Rnd_HE_Grenade_shell",12,1},{"OPTRE_1Rnd_Smoke_Grenade_shell",4,1},{"OPTRE_1Rnd_SmokeRed_Grenade_shell",2,1}}},"TCF_Frihelm_W","TCF_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Anti_Tank : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Anti Tank";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Vest_UP","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_FRI_Vest_UP","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"TCF_ARM37","OPTRE_M41_SSR","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"TCF_ARM37","OPTRE_M41_SSR","TCF_M6B_Wood","Binocular"};

        magazines[] = {"TCF_32Rnd_762x51_Mag_APT","OPTRE_M41_Twin_HEAT","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"TCF_32Rnd_762x51_Mag_APT","OPTRE_M41_Twin_HEAT","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};

        backpack = "TCF_RUCKSACK_UNSC_WDL_F";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARM37","","","TCF_SENT_CG",{"TCF_32Rnd_762x51_Mag_APT",32},{},""},{"OPTRE_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT",2},{},""},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Vest_UP",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",1},{"TCF_32Rnd_762x51_Mag_APT",8,32}}},{"TCF_RUCKSACK_UNSC_WDL_F",{{"OPTRE_M41_Twin_HEAT",2,2}}},"TCF_Frihelm_W","TCF_URB_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Anti_Air : O_NFM_Anti_Tank {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Anti Air";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Vest_UP","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_FRI_Vest_UP","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"TCF_ARM37","OPTRE_M41_SSR","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"TCF_ARM37","OPTRE_M41_SSR","TCF_M6B_Wood","Binocular"};

        magazines[] = {"TCF_32Rnd_762x51_Mag_APT","OPTRE_M41_Twin_HEAT_G","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"TCF_32Rnd_762x51_Mag_APT","OPTRE_M41_Twin_HEAT_G","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};

        backpack = "TCF_RUCKSACK_UNSC_WDL_F";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARM37","","","TCF_SENT_CG",{"TCF_32Rnd_762x51_Mag_APT",32},{},""},{"OPTRE_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT_G",2},{},""},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Vest_UP",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",1},{"TCF_32Rnd_762x51_Mag_APT",8,32}}},{"TCF_RUCKSACK_UNSC_WDL_F",{{"OPTRE_M41_Twin_HEAT_G",3,2}}},"TCF_Frihelm_W","TCF_URB_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Medic : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Vest_UP","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_FRI_Vest_UP","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"TCF_ARM37","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"TCF_ARM37","TCF_M6B_Wood","Binocular"};

        magazines[] = {"TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Medic";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARM37","","","TCF_SENT_CG",{"TCF_32Rnd_762x51_Mag_APT",32},{},""},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Vest_UP",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",2},{"TCF_32Rnd_762x51_Mag_APT",8,32}}},{"OPTRE_UNSC_Rucksack_Medic",{{"ACE_fieldDressing",40},{"ACE_elasticBandage",30},{"ACE_packingBandage",30},{"ACE_quikclot",40},{"ACE_epinephrine",6},{"ACE_morphine",2},{"ACE_salineIV_500",4},{"ACE_salineIV_250",6},{"ACE_salineIV",2},{"ACE_tourniquet",8},{"ACE_splint",4},{"ACE_painkillers",2,10}}},"TCF_Frihelm_W","TCF_BRW_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Sniper : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Rig","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"TCF_FRI_Rig","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"};

        weapons[] = {"OPTRE_SRS99C","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"OPTRE_SRS99C","TCF_M6B_Wood","Binocular"};

        magazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_AP_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_AP_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_AP_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRS99C","","","OPTRE_SRS99C_Scope",{"OPTRE_4Rnd_145x114_APFSDS_Mag",4},{},""},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Rig",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",1},{"OPTRE_4Rnd_145x114_APFSDS_Mag",9,4}}},{},"TCF_Frihelm_W","TCF_DES_UP_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Autorifleman : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Vest","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_FRI_Vest","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"TCF_M73H","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"TCF_M73H","TCF_M6B_Wood","Binocular"};

        magazines[] = {"TCF_300Rnd_95x60_Box_HPSAPT","OPTRE_8Rnd_127x40_AP_Mag","TCF_300Rnd_95x60_Box_HPSAPT","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"TCF_300Rnd_95x60_Box_HPSAPT","OPTRE_8Rnd_127x40_AP_Mag","TCF_300Rnd_95x60_Box_HPSAPT","OPTRE_8Rnd_127x40_AP_Mag"};

        backpack = "TCF_RUCKSACK_UNSC_WDL_F";

        ALiVE_orbatCreator_loadout[] = {{"TCF_M73H","","","OPTRE_M73_SmartLink",{"TCF_300Rnd_95x60_Box_HPSAPT",300},{},"bipod_01_F_blk"},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_NVG",1},{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1}}},{"TCF_FRI_Vest",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"TCF_300Rnd_95x60_Box_HPSAPT",1,300}}},{"TCF_RUCKSACK_UNSC_WDL_F",{{"TCF_300Rnd_95x60_Box_HPSAPT",1,300}}},"TCF_Frihelm_W","TCF_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Team_Leader : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Vest_UP","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_FRI_Vest_UP","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"TCF_ARM37_SHT","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"TCF_ARM37_SHT","TCF_M6B_Wood","Binocular"};

        magazines[] = {"TCF_32Rnd_762x51_Mag_APT","6Rnd_12Gauge_Slug","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","6Rnd_12Gauge_Slug","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"TCF_32Rnd_762x51_Mag_APT","6Rnd_12Gauge_Slug","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","6Rnd_12Gauge_Slug","OPTRE_8Rnd_127x40_AP_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARM37_SHT","","","TCF_SENT_CG",{"TCF_32Rnd_762x51_Mag_APT",32},{"6Rnd_12Gauge_Slug",6},""},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Vest_UP",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",1},{"TCF_32Rnd_762x51_Mag_APT",8,32},{"6Rnd_12Gauge_Slug",4,6}}},{},"TCF_Frihelm_W","TCF_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Squad_Leader : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Vest_UP","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"TCF_FRI_Vest_UP","TCF_Frihelm_W","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"};

        weapons[] = {"TCF_ARM37_GL","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"TCF_ARM37_GL","TCF_M6B_Wood","Binocular"};

        magazines[] = {"TCF_32Rnd_762x51_Mag_APT","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"TCF_32Rnd_762x51_Mag_APT","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_AP_Mag","TCF_32Rnd_762x51_Mag_APT","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_AP_Mag"};

        backpack = "TCF_RUCKSACK_UNSC_URA_RAD_F";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARM37_GL","","","TCF_SENT_CG",{"TCF_32Rnd_762x51_Mag_APT",32},{"1Rnd_HE_Grenade_shell",1},""},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Vest_UP",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",1},{"TCF_32Rnd_762x51_Mag_APT",8,32}}},{"TCF_RUCKSACK_UNSC_URA_RAD_F",{{"1Rnd_HE_Grenade_shell",16,1},{"OPTRE_1Rnd_Smoke_Grenade_shell",8,1},{"OPTRE_1Rnd_SmokeRed_Grenade_shell",2,1},{"OPTRE_1Rnd_SmokeYellow_Grenade_shell",2,1},{"OPTRE_1Rnd_SmokeBlue_Grenade_shell",2,1}}},"TCF_Frihelm_W","TCF_BRW_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Officer : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Vest_UP","Frieden_Black_beret","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"TCF_FRI_Vest_UP","Frieden_Black_beret","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"};

        weapons[] = {"TCF_ARM37_DMR","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"TCF_ARM37_DMR","TCF_M6B_Wood","Binocular"};

        magazines[] = {"TCF_15Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag","TCF_15Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"TCF_15Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag","TCF_15Rnd_762x51_Mag_APT","OPTRE_8Rnd_127x40_AP_Mag"};

        backpack = "TCF_RUCKSACK_UNSC_URA_RAD_F";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARM37_DMR","","","OPTRE_M392_Scope",{"TCF_15Rnd_762x51_Mag_APT",15},{},"bipod_01_F_blk"},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Vest_UP",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",1},{"TCF_15Rnd_762x51_Mag_APT",10,15}}},{"TCF_RUCKSACK_UNSC_URA_RAD_F",{}},"Frieden_Black_beret","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Crewman : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Rig","OPTRE_UNSC_VX16_HelmetNV","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"TCF_FRI_Rig","OPTRE_UNSC_VX16_HelmetNV","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"};

        weapons[] = {"OPTRE_M7","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"OPTRE_M7","TCF_M6B_Wood","Binocular"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","OPTRE_M7_Sight",{"OPTRE_60Rnd_5x23mm_Mag_tracer",60},{},""},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Rig",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_60Rnd_5x23mm_Mag_tracer",4,60}}},{},"OPTRE_UNSC_VX16_HelmetNV","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Pilot : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Rig","OPTRE_UNSC_VX16_HelmetV","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"TCF_FRI_Rig","OPTRE_UNSC_VX16_HelmetV","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"};

        weapons[] = {"OPTRE_M7","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"OPTRE_M7","TCF_M6B_Wood","Binocular"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","OPTRE_M7_Sight",{"OPTRE_60Rnd_5x23mm_Mag_tracer",60},{},""},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Rig",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_60Rnd_5x23mm_Mag_tracer",4,60}}},{},"OPTRE_UNSC_VX16_HelmetV","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_Patrol : O_NFM_Rifleman {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "Patrol";
        side = 0;
        faction = "o_nfm";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â¿"};

        uniformClass = "TCF_FRI_uni_Base_W";

        linkedItems[] = {"TCF_FRI_Rig","TCF_MC_AUTUMN","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_FRI_Rig","TCF_MC_AUTUMN","ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_M7","TCF_M6B_Wood","Binocular"};
        respawnWeapons[] = {"OPTRE_M7","TCF_M6B_Wood","Binocular"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_AP_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","OPTRE_M7_Sight",{"OPTRE_60Rnd_5x23mm_Mag_tracer",60},{},""},{},{"TCF_M6B_Wood","","TCF_M6_Flashlight_IR","OPTRE_M6C_Scope",{"OPTRE_8Rnd_127x40_AP_Mag",8},{},""},{"TCF_FRI_uni_Base_W",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_8Rnd_127x40_AP_Mag",3,8}}},{"TCF_FRI_Rig",{{"ACE_fieldDressing",5},{"ACE_elasticBandage",5},{"ACE_tourniquet",4},{"ACE_splint",2},{"ACE_quikclot",5},{"ACE_packingBandage",5},{"OPTRE_NVG",1},{"OPTRE_60Rnd_5x23mm_Mag_tracer",8,60}}},{},"TCF_MC_AUTUMN","TCF_Shemagh",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_pnr1000a","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_AV_14_Hornet : OPTRE_UNSC_hornet_CAS_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "AV-14 Hornet";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Pilot";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles_Air\hornet\data\hornet_hull_innie2_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorinnie2";

    };

    class O_ONFM_M412_Bison_IFV : OPTRE_M412_IFV_UNSC_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M412 Bison IFV";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_NFM_Crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Bison\data\Bison_Body_standard_CO.paa'];_unit setObjectTextureGlobal [1,'OPTRE_Vehicles\Bison\data\Bison_Misc_standard_CO.paa'];_unit setObjectTextureGlobal [2,'OPTRE_Vehicles\Bison\data\Bison_WheelsCannon_CO.paa'];_unit setObjectTextureGlobal [3,'OPTRE_Vehicles\Bison\data\Bison_Seats_CO.paa'];_unit setObjectTextureGlobal [4,'OPTRE_Vehicles\Bison\data\Bison_Interior_CO.paa'];_unit setObjectTextureGlobal [5,'OPTRE_Vehicles\Bison\data\Bison_MFCDScreens_CO.paa'];_unit setObjectTextureGlobal [6,'OPTRE_Vehicles\Bison\data\Bison_90mm_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class O_NFM_M12_LRV : OPTRE_M12_LRV_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12 LRV (MG)";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Rifleman";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_NFM_Marksman"; };
            class MainTurret : MainTurret { gunnerType = "O_NFM_Rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extupper_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extunder_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles\Warthog\data\turrets\m12_turret_co.paa'];_unit setObjectTextureGlobal [3,'\OPTRE_Vehicles\warthog\data\decals_ca.paa'];_unit setObjectTextureGlobal [4,'\OPTRE_Vehicles\warthog\data\m12hogmaav_interior_co.paa'];_unit setObjectTextureGlobal [5,'\OPTRE_Vehicles\warthog\data\turrets\m12_turret_decals_ca.paa'];_unit setObjectTextureGlobal [6,'\OPTRE_Vehicles\warthog\data\turrets\sight_co.paa'];_unit setObjectTextureGlobal [7,'\OPTRE_Vehicles\warthog\data\apc_lopo_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorstand";

    };

    class O_NFM_M12R_AA : OPTRE_M12R_AA_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12R (AA)";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Marksman";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_NFM_Rifleman"; };
            class MainTurret : MainTurret { gunnerType = "O_NFM_Rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_M12A1_AT : OPTRE_M12A1_LRV_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12A1 (AT)";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Rifleman";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_NFM_Rifleman"; };
            class MainTurret : MainTurret { gunnerType = "O_NFM_Marksman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extupper_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extunder_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles\Warthog\data\turrets\m12_turret_co.paa'];_unit setObjectTextureGlobal [3,'\OPTRE_Vehicles\warthog\data\decals_ca.paa'];_unit setObjectTextureGlobal [4,'\OPTRE_Vehicles\warthog\data\m12hogmaav_interior_co.paa'];_unit setObjectTextureGlobal [5,'\OPTRE_Vehicles\warthog\data\turrets\m39_turret_co.paa'];_unit setObjectTextureGlobal [6,'\OPTRE_Vehicles\warthog\data\turrets\m12_turret_decals_ca.paa'];_unit setObjectTextureGlobal [7,'\OPTRE_Vehicles\warthog\data\apc_lopo_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorstand";

    };

    class O_NFM_M12_APC : OPTRE_M12_FAV_APC_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12 APC";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Rifleman";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extupper_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extunder_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles\Warthog\data\transp_lopo_co.paa'];_unit setObjectTextureGlobal [3,'\OPTRE_Vehicles\Warthog\data\apc_lopo_co.paa'];_unit setObjectTextureGlobal [4,'\OPTRE_Vehicles\warthog\data\decals_ca.paa'];_unit setObjectTextureGlobal [5,'\OPTRE_Vehicles\warthog\data\m12hogmaav_interior_co.paa'];_unit setObjectTextureGlobal [6,'\OPTRE_Vehicles\warthog\data\warthog_transport_decals_ca.paa'];_unit setObjectTextureGlobal [7,'\OPTRE_Vehicles\warthog\data\warthog_transport_net_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorstand";

    };

    class O_NFM_M831_Troop_Transport : OPTRE_M813_TT_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M831 Troop Transport";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Rifleman";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = ""; };
            class CargoGunner_02 : CargoGunner_02 { gunnerType = ""; };
            class CargoGunner_03 : CargoGunner_03 { gunnerType = ""; };
            class CargoGunner_04 : CargoGunner_04 { gunnerType = ""; };
            class CargoGunner_05 : CargoGunner_05 { gunnerType = ""; };
            class CargoGunner_06 : CargoGunner_06 { gunnerType = ""; };
            class CargoGunner_07 : CargoGunner_07 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extupper_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extunder_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles\Warthog\data\transp_lopo_co.paa'];_unit setObjectTextureGlobal [3,'\OPTRE_Vehicles\warthog\data\decals_ca.paa'];_unit setObjectTextureGlobal [4,'\OPTRE_Vehicles\warthog\data\m12hogmaav_interior_co.paa'];_unit setObjectTextureGlobal [5,'\OPTRE_Vehicles\warthog\data\warthog_transport_net_ca.paa'];_unit setObjectTextureGlobal [6,'\OPTRE_Vehicles\warthog\data\warthog_transport_decals_ca.paa'];_unit setObjectTextureGlobal [7,'\OPTRE_Vehicles\warthog\data\apc_lopo_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorstand";

    };

    class O_NFM_M8008B_Scorpion_MBT : OPTRE_M808B_UNSC_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M8008B Scorpion MBT";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_NFM_Crewman"; };
            class CargoTurret1 : CargoTurret1 { gunnerType = ""; };
            class CargoTurret2 : CargoTurret2 { gunnerType = ""; };
            class CargoTurret3 : CargoTurret3 { gunnerType = ""; };
            class CargoTurret4 : CargoTurret4 { gunnerType = ""; };
            class CargoTurret5 : CargoTurret5 { gunnerType = ""; };
            class CargoTurret6 : CargoTurret6 { gunnerType = ""; };
            class CargoTurret7 : CargoTurret7 { gunnerType = ""; };
            class CargoTurret8 : CargoTurret8 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles_Tracked\Scorpion\data\texture\scorp_lopo_co.paa'];_unit setObjectTextureGlobal [1,'OPTRE_Vehicles_Tracked\Scorpion\data\texture\scorp_tur_wood_co.paa'];_unit setObjectTextureGlobal [2,'OPTRE_Vehicles_Tracked\Scorpion\data\texture\det_3_co.paa'];_unit setObjectTextureGlobal [3,'OPTRE_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa'];_unit setObjectTextureGlobal [4,'OPTRE_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa'];_unit setObjectTextureGlobal [5,'OPTRE_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa'];_unit setObjectTextureGlobal [6,'OPTRE_Vehicles_Tracked\Scorpion\data\texture\mine_roller_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorstand";

    };

    class O_NFM_D77H_TCI_AV_Pelican : OPTRE_Pelican_armed_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "D77H-TCI/AV Pelican";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Pilot";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "O_NFM_Pilot"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Pelican\data\PelicanExterior_innie_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorinnie";

    };

    class O_NFM_M1015_Mule_MLR : OPTRE_m1015_mule_mlr_ins_IND_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M1015 Mule (MLR)";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_NFM_Crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_AU_44 : OPTRE_AU_44_INS_Mortar_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "AU-44";
        side = 0;
        faction = "o_nfm";
        crew = "OPTRE_Ins_URF_Rifleman_AR";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_NFM_Rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_LAU_65D_SGM_151 : OPTRE_LAU65D_pod_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "LAU-65D/SGM-151";
        side = 0;
        faction = "o_nfm";
        crew = "Civilian";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_NFM_Crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ONFM_M494_Oryx_IFV : OPTRE_M494_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M494 Oryx IFV";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Crewman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_NFM_Crewman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles_Tracked\Oryx\data\texture\oryx_armor_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles_Tracked\Oryx\data\texture\oryx_main_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles_Tracked\Oryx\data\texture\oryx_net_ca.paa'];_unit setObjectTextureGlobal [3,'\OPTRE_Vehicles_Tracked\Oryx\data\texture\oryx_net_ca.paa'];_unit setObjectTextureGlobal [4,'\OPTRE_Vehicles_Tracked\Oryx\data\texture\oryx_net_ca.paa'];_unit setObjectTextureGlobal [5,'\OPTRE_Vehicles_Tracked\Oryx\data\texture\oryx_turret_co.paa'];_unit setObjectTextureGlobal [6,'\OPTRE_Vehicles_Tracked\Oryx\data\texture\scorpion_mg_co.paa'];_unit setObjectTextureGlobal [7,'\OPTRE_Vehicles_Tracked\Oryx\data\Texture\oryx_decal_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorstand";

    };

    class O_NFM_M79_AA_Turret : OPTRE_Static_AA_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M79 AA Turret";
        side = 0;
        faction = "o_nfm";
        crew = "OPTRE_UNSC_Army_Soldier_Rifleman_AR_WDL";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_NFM_Rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_FG75_Field_Gun : OPTRE_Static_FG75_IND_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "FG75 Field Gun";
        side = 0;
        faction = "o_nfm";
        crew = "OPTRE_Ins_URF_Engineer";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_NFM_Rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_M112_Wet_Patrol_Craft_MG : optre_catfish_mg_f_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M112 Wet Patrol Craft (MG)";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Rifleman";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class MainTurret : MainTurret { gunnerType = "O_NFM_Marksman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_M112_Wet_Patrol_Craft_Unarmed : optre_catfish_unarmed_f_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M112 Wet Patrol Craft (Unarmed)";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Rifleman";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_NFM_MH_144S_Falcon : OPTRE_UNSC_falcon_armed_S_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "MH-144S Falcon";
        side = 0;
        faction = "o_nfm";
        crew = "O_NFM_Pilot";

        class Turrets : Turrets {
            class LeftDoorGun : LeftDoorGun { gunnerType = "O_NFM_Crewman"; };
            class RightDoorGun : RightDoorGun { gunnerType = "O_NFM_Crewman"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles_Air\Falcon\data\Innie\Falcon_Innie_Standard_Main_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles_Air\Falcon\data\Innie\Falcon_Innie_Standard_Attachments_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles_Air\Falcon\data\Falcon_Interior_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Innie";

    };

    class O_ONFM_M41_LAAG_Turret : OPTRE_Static_M41_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "M41 LAAG Turret";
        side = 0;
        faction = "o_nfm";
        crew = "OPTRE_UNSC_Army_Soldier_Rifleman_AR_WDL";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_NFM_Rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ONFM_AT_Rocket_Turret : OPTRE_Static_ATGM_OCimport_02 {
        author = "P01. N. Knight";
        scope = 2;
        scopeCurator = 2;
        displayName = "AT Rocket Turret";
        side = 0;
        faction = "O_NFM";
        crew = "OPTRE_UNSC_Army_Soldier_Rifleman_AR_WDL";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_NFM_Rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};