//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.5.2409021
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_BDCUNSC {
        displayName = "Black Dagger Company";
        side = 1;
        flag = "BDA_Core\BDA_UI\flags\BDA_BlackDagger_Ca.paa";
        icon = "BDA_Core\BDA_UI\flags\BDA_BlackDagger_Ca.paa";
        priority = 0;
    };
};