//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.5.2409021
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class B_Survivor_F;
    class B_Survivor_F_OCimport_01 : B_Survivor_F { scope = 0; class EventHandlers; };
    class B_Survivor_F_OCimport_02 : B_Survivor_F_OCimport_01 { class EventHandlers; };

    class B_soldier_F;
    class B_soldier_F_OCimport_01 : B_soldier_F { scope = 0; class EventHandlers; };
    class B_soldier_F_OCimport_02 : B_soldier_F_OCimport_01 { class EventHandlers; };

    class B_soldier_AR_F;
    class B_soldier_AR_F_OCimport_01 : B_soldier_AR_F { scope = 0; class EventHandlers; };
    class B_soldier_AR_F_OCimport_02 : B_soldier_AR_F_OCimport_01 { class EventHandlers; };

    class B_medic_F;
    class B_medic_F_OCimport_01 : B_medic_F { scope = 0; class EventHandlers; };
    class B_medic_F_OCimport_02 : B_medic_F_OCimport_01 { class EventHandlers; };

    class B_soldier_exp_F;
    class B_soldier_exp_F_OCimport_01 : B_soldier_exp_F { scope = 0; class EventHandlers; };
    class B_soldier_exp_F_OCimport_02 : B_soldier_exp_F_OCimport_01 { class EventHandlers; };

    class B_soldier_AT_F;
    class B_soldier_AT_F_OCimport_01 : B_soldier_AT_F { scope = 0; class EventHandlers; };
    class B_soldier_AT_F_OCimport_02 : B_soldier_AT_F_OCimport_01 { class EventHandlers; };

    class B_Soldier_SL_F;
    class B_Soldier_SL_F_OCimport_01 : B_Soldier_SL_F { scope = 0; class EventHandlers; };
    class B_Soldier_SL_F_OCimport_02 : B_Soldier_SL_F_OCimport_01 { class EventHandlers; };

    class B_Soldier_TL_F;
    class B_Soldier_TL_F_OCimport_01 : B_Soldier_TL_F { scope = 0; class EventHandlers; };
    class B_Soldier_TL_F_OCimport_02 : B_Soldier_TL_F_OCimport_01 { class EventHandlers; };

    class B_Sharpshooter_F;
    class B_Sharpshooter_F_OCimport_01 : B_Sharpshooter_F { scope = 0; class EventHandlers; };
    class B_Sharpshooter_F_OCimport_02 : B_Sharpshooter_F_OCimport_01 { class EventHandlers; };

    class B_crew_F;
    class B_crew_F_OCimport_01 : B_crew_F { scope = 0; class EventHandlers; };
    class B_crew_F_OCimport_02 : B_crew_F_OCimport_01 { class EventHandlers; };

    class B_BDA_Rook : B_Survivor_F_OCimport_02 {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Rook.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rookie";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_UNSC_PT_ODST_Uniform";

        linkedItems[] = {"OPTRE_UNSC_Cap_ODST","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"OPTRE_UNSC_Cap_ODST","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"OPTRE_UNSC_PT_ODST_Uniform",{{"FirstAidKit",1}}},{},{},"OPTRE_UNSC_Cap_ODST","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter",""}};

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'BDA_AZ_Sword'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "BDA_AZ_Sword";

    };

    class B_BDA_Rifleman: B_soldier_F_OCimport_02 {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Rifleman.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_RF",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_Autorifleman : B_soldier_AR_F_OCimport_02 {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Autorifleman.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_M73","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M73","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_100Rnd_95x40_Box_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_100Rnd_95x40_Box_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_100Rnd_95x40_Box_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_100Rnd_95x40_Box_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M73","","","OPTRE_M73_SmartLink",{"TCF_100Rnd_95x40_Box_JHP",100},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1}}},{"BDA_Armor_RF",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"OPTRE_100Rnd_95x40_Box",6,100},{"OPTRE_12Rnd_127x40_Mag",3,12}}},"BDA_CH252D_Helmet","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_SquadLead : B_Soldier_SL_F_OCimport_02 {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_SquadLead.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Smartfinder"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries"};

        backpack = "BDA_Rucksack_B_SL";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1}}},{"BDA_Armor_RF",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"OPTRE_M2_Smoke_Red",2,1},{"OPTRE_M2_Smoke_Purple",1,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B_SL",{{"ACE_MapTools",1},{"ItemcTabHCam",1},{"MineDetector",1},{"OPTRE_M2_Smoke_Yellow",2,1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet","",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_Medic : B_medic_F_OCimport_02 {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Medic.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_MD","BDA_CH252D_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_MD","BDA_CH252D_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_BR55_Grey","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_BR55_Grey","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag_Tracer","TCF_12Rnd_127x40_Mag_JHP","OPTRE_36Rnd_95x40_Mag_Tracer","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag_Tracer","TCF_12Rnd_127x40_Mag_JHP","OPTRE_36Rnd_95x40_Mag_Tracer","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B_Medical";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_BR55_Grey","","","",{"OPTRE_36Rnd_95x40_Mag_Tracer",36},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ItemcTabHCam",1},{"ACE_IR_Strobe_Item",2},{"OPTRE_M9_Frag",2,1},{"TCF_12Rnd_127x40_Mag_JHP",2,12}}},{"BDA_Armor_MD",{{"OPTRE_36Rnd_95x40_Mag_Tracer",12,36}}},{"BDA_Rucksack_B_Medical",{{"ACE_epinephrine",10},{"ACE_morphine",3},{"ACE_splint",8},{"ACE_tourniquet",6},{"ACE_surgicalKit",1},{"ACE_salineIV_500",6},{"ACE_salineIV_250",6},{"ACE_salineIV",6},{"ACE_packingBandage",30},{"ACE_elasticBandage",50},{"ACE_fieldDressing",20},{"ACE_EntrenchingTool",1},{"ACE_CableTie",3},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"OPTRE_M2_Smoke_Purple",2,1},{"ACE_painkillers",2,10},{"TCF_12Rnd_127x40_Mag_JHP",2,12},{"TCF_36Rnd_95x40_Mag_JHP",8,36}}},"BDA_CH252D_Helmet","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};

        medic = 1;
        ace_medical_MedicalClass = 2;

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_Demo : B_soldier_exp_F_OCimport_02 {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Demo.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Demolitions";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_DM","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_DM","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_EntrenchingTool",1}}},{"BDA_Armor_DM",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"ACE_IR_Strobe_Item",1},{"ACE_CableTie",3},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B_Heavy",{{"MineDetector",1},{"ItemcTabHCam",1},{"ACE_M26_Clacker",1},{"ACE_DefusalKit",1},{"ace_marker_flags_white",5},{"ace_marker_flags_red",20},{"ace_marker_flags_blue",5},{"C7_Remote_Mag",4,1},{"C12_Remote_Mag",2,1},{"TCF_60Rnd_762x51_Mag_JHP",8,60},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};

        ace_engineer = 1;
        ace_engineer_engineerclass = 1;
        ace_isEOD = 1;
        explosiveSpecialist = 1;

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_Rocket : B_soldier_AT_F_OCimport_02 {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Rocket.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rocket Jockey";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M41_SSR","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M41_SSR","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","OPTRE_M41_Twin_HEAT_SACLOS","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","OPTRE_M41_Twin_HEAT_SACLOS","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{"OPTRE_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT_SACLOS",2},{},""},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_RF",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B_Heavy",{{"ItemcTabHCam",1},{"OPTRE_M41_Twin_HEAT_G",2,2},{"OPTRE_M41_Twin_HEAT_SACLOS",1,2},{"TCF_12Rnd_127x40_Mag_JHP",2,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_Teamleader : B_BDA_SquadLead {
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default.jpg"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Smartfinder"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries"};

        backpack = "BDA_Rucksack_B_SL";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1}}},{"BDA_Armor_RF",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"OPTRE_M2_Smoke_Red",2,1},{"OPTRE_M2_Smoke_Purple",1,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B_SL",{{"ACE_MapTools",1},{"ItemcTabHCam",1},{"MineDetector",1},{"OPTRE_M2_Smoke_Yellow",2,1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet","",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_Breacher : B_Soldier_TL_F_OCimport_02 {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Breacher.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Breacher";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_BR","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_BR","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","OPTRE_12Rnd_127x40_Mag","TCF_60Rnd_762x51_Mag_JHP","OPTRE_12Rnd_127x40_Mag"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","OPTRE_12Rnd_127x40_Mag","TCF_60Rnd_762x51_Mag_JHP","OPTRE_12Rnd_127x40_Mag"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",12},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3},{"TCF_60Rnd_762x51_Mag_JHP",1,60}}},{"BDA_Armor_BR",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"ACE_wirecutter",1},{"OPTRE_12Rnd_8Gauge_Slugs",2,12},{"OPTRE_60Rnd_762x51_Mag",8,60},{"OPTRE_12Rnd_127x40_Mag",1,12},{{"OPTRE_M90A","","","",{},{},""},1}}},"BDA_CH252D_Helmet","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_Sniper : B_Sharpshooter_F_OCimport_02 {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Sniper.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_SN","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG_MVI_UL"};
        respawnlinkedItems[] = {"BDA_Armor_SN","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG_MVI_UL"};

        weapons[] = {"OPTRE_SRS99D","OPTRE_M6C","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_SRS99D","OPTRE_M6C","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag_D","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries","OPTRE_4Rnd_145x114_APFSDS_Mag_D","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag_D","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries","OPTRE_4Rnd_145x114_APFSDS_Mag_D","TCF_12Rnd_127x40_Mag_JHP","Laserbatteries"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRS99D","","","OPTRE_SRS99_Scope",{"OPTRE_4Rnd_145x114_APFSDS_Mag_D",4},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_SN",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ACE_Tripod",1},{"ItemcTabHCam",1},{"OPTRE_4Rnd_145x114_APFSDS_Mag",12,4},{"TCF_12Rnd_127x40_Mag_JHP",5,12}}},"BDA_CH252D_Helmet","",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG_MVI_UL"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_1_1 : B_BDA_Rifleman {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_1_1.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "1-1";
        side = 1;
        faction = "B_BDCUNSC";
        editorSubcategory = "BDA_ESC_Squads";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF_S1","BDA_CH252D_Helmet_S1","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF_S1","BDA_CH252D_Helmet_S1","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_RF_S1",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet_S1","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_1_2 : B_BDA_Rifleman {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_1_2.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "1-2";
        side = 1;
        faction = "B_BDCUNSC";
        editorSubcategory = "BDA_ESC_Squads";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF_S2","BDA_CH252D_Helmet_S2","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF_S2","BDA_CH252D_Helmet_S2","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_RF_S2",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet_S2","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_1_3 : B_BDA_Rifleman {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_1_3.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "1-3";
        side = 1;
        faction = "B_BDCUNSC";
        editorSubcategory = "BDA_ESC_Squads";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF_S3","BDA_CH252D_Helmet_S3","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF_S3","BDA_CH252D_Helmet_S3","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_RF_S3",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet_S3","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_2_1 : B_BDA_Rifleman {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_2_1.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "2-1";
        side = 1;
        faction = "B_BDCUNSC";
        editorSubcategory = "BDA_ESC_Squads";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF_S4","BDA_CH252D_Helmet_S4","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF_S4","BDA_CH252D_Helmet_S4","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_RF_S4",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet_S4","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_2_2 : B_BDA_Rifleman {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_2_2.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "2-2";
        side = 1;
        faction = "B_BDCUNSC";
        editorSubcategory = "BDA_ESC_Squads";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF_S5","BDA_CH252D_Helmet_S5","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF_S5","BDA_CH252D_Helmet_S5","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_RF_S5",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet_S5","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_2_3 : B_BDA_Rifleman {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_2_3.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "2-3";
        side = 1;
        faction = "B_BDCUNSC";
        editorSubcategory = "BDA_ESC_Squads";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF_S6","BDA_CH252D_Helmet_S6","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF_S6","BDA_CH252D_Helmet_S6","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_RF_S6",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet_S6","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_1_0 : B_BDA_Rifleman {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_1_0.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "1st Platoon";
        side = 1;
        faction = "B_BDCUNSC";
        editorSubcategory = "BDA_ESC_Squads";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF_P1","BDA_CH252D_Helmet_P1","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF_P1","BDA_CH252D_Helmet_P1","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_RF_P1",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet_P1","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};

        ace_engineer = 1;

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_2_0 : B_BDA_Rifleman {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_2_0.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "2nd Platoon";
        side = 1;
        faction = "B_BDCUNSC";
        editorSubcategory = "BDA_ESC_Squads";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF_P2","BDA_CH252D_Helmet_P2","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF_P2","BDA_CH252D_Helmet_P2","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink",{"TCF_60Rnd_762x51_Mag_JHP",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",3}}},{"BDA_Armor_RF_P2",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"TCF_12Rnd_127x40_Mag_JHP",3,12},{"OPTRE_60Rnd_762x51_Mag",8,60}}},"BDA_CH252D_Helmet_P2","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};

        ace_engineer = 1;

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_Grenadier : B_BDA_Rifleman {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Grenadier.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B_SL";

        linkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"BDA_Armor_RF","BDA_CH252D_Helmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5BGL","OPTRE_M6C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5BGL","OPTRE_M6C","OPTRE_Binoculars"};

        magazines[] = {"TCF_60Rnd_762x51_Mag_JHP","1Rnd_HE_Grenade_shell","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","1Rnd_HE_Grenade_shell","TCF_12Rnd_127x40_Mag_JHP"};
        respawnMagazines[] = {"TCF_60Rnd_762x51_Mag_JHP","1Rnd_HE_Grenade_shell","TCF_12Rnd_127x40_Mag_JHP","TCF_60Rnd_762x51_Mag_JHP","1Rnd_HE_Grenade_shell","TCF_12Rnd_127x40_Mag_JHP"};

        backpack = "BDA_Rucksack_B";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5BGL","","","",{"TCF_60Rnd_762x51_Mag_JHP",60},{"1Rnd_HE_Grenade_shell",1},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"TCF_12Rnd_127x40_Mag_JHP",12},{},""},{"BDA_Uniform_B_SL",{{"ACE_CableTie",6},{"ACE_EntrenchingTool",1},{"ACE_IR_Strobe_Item",1},{"TCF_12Rnd_127x40_Mag_JHP",1,12}}},{"BDA_Armor_RF",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"ACE_HuntIR_monitor",1},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M2_Smoke_Blue",2,1},{"TCF_12Rnd_127x40_Mag_JHP",1,12},{"ACE_painkillers",1,10}}},{"BDA_Rucksack_B",{{"ItemcTabHCam",1},{"1Rnd_HE_Grenade_shell",25,1},{"ACE_HuntIR_M203",5,1},{"OPTRE_1Rnd_Smoke_Grenade_shell",6,1},{"OPTRE_1Rnd_SmokeBlue_Grenade_shell",4,1},{"OPTRE_1Rnd_SmokeRed_Grenade_shell",4,1},{"ACE_40mm_Flare_white",5,1},{"OPTRE_12Rnd_127x40_Mag",2,12},{"OPTRE_60Rnd_762x51_Mag",8,60},{"1Rnd_SmokeBlue_Grenade_shell",2,1},{"1Rnd_SmokeRed_Grenade_shell",2,1},{"1Rnd_Smoke_Grenade_shell",2,1}}},"BDA_CH252D_Helmet","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_Pilot : B_BDA_Rook {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Pilot.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Navy_Uniform_Avi2";

        linkedItems[] = {"BDA_M52B_Pilot_Armor_G","BDA_Heli_Pilot_Helmet_G","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","TFAR_microdagr"};
        respawnlinkedItems[] = {"BDA_M52B_Pilot_Armor_G","BDA_Heli_Pilot_Helmet_G","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","TFAR_microdagr"};

        weapons[] = {"OPTRE_M7","OPTRE_M6C","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6C","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries","OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries","OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};

        backpack = "BDA_Naval_Belt_R";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","OPTRE_M6C_compensator","","",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"BDA_Navy_Uniform_Avi2",{{"ACE_IR_Strobe_Item",2}}},{"BDA_M52B_Pilot_Armor_G",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M2_Smoke_Blue",2,1},{"OPTRE_M2_Smoke_Red",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M9_Frag",2,1},{"OPTRE_12Rnd_127x40_Mag",2,12},{"ACE_painkillers",1,10},{"TCF_48Rnd_5x23mm_Mag_HV",8,48}}},{"BDA_Naval_Belt_R",{{"ToolKit",1},{"ItemcTabHCam",1}}},"BDA_Heli_Pilot_Helmet_G","",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","TFAR_microdagr",""}};

        ace_engineer = 2;

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_PilotLead : B_BDA_Rook {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_PilotLead.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Lead Pilot";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Navy_Uniform_Avi1";

        linkedItems[] = {"BDA_M52B_Pilot_Armor_B","BDA_Heli_Pilot_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","TFAR_microdagr"};
        respawnlinkedItems[] = {"BDA_M52B_Pilot_Armor_B","BDA_Heli_Pilot_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","TFAR_microdagr"};

        weapons[] = {"OPTRE_M7","OPTRE_M6C","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6C","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries","OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries","OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};

        backpack = "BDA_Naval_Belt_R";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","OPTRE_M6C_compensator","","",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"BDA_Navy_Uniform_Avi1",{{"ACE_IR_Strobe_Item",2}}},{"BDA_M52B_Pilot_Armor_B",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M2_Smoke_Blue",2,1},{"OPTRE_M2_Smoke_Red",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M9_Frag",2,1},{"OPTRE_12Rnd_127x40_Mag",2,12},{"ACE_painkillers",1,10},{"TCF_48Rnd_5x23mm_Mag_HV",8,48}}},{"BDA_Naval_Belt_R",{{"ToolKit",1},{"ItemcTabHCam",1}}},"BDA_Heli_Pilot_Helmet","",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","TFAR_microdagr",""}};

        ace_engineer = 2;
        ace_medical_MedicalClass = 1;

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BDA_Crewman : B_crew_F_OCimport_02 {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Crewman.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 1;
        faction = "B_BDCUNSC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Navy_Uniform_Avi2";

        linkedItems[] = {"BDA_Armor_Pilot","BDA_VX19_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","TFAR_microdagr"};
        respawnlinkedItems[] = {"BDA_Armor_Pilot","BDA_VX19_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","TFAR_microdagr"};

        weapons[] = {"OPTRE_M7","OPTRE_M6C","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6C","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries","OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries","OPTRE_60Rnd_5x23mm_Mag","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","OPTRE_M6C_compensator","","",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"OPTRE_M6C","OPTRE_M6C_compensator","","",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"BDA_Navy_Uniform_Avi2",{{"ACE_IR_Strobe_Item",2}}},{"BDA_Armor_Pilot",{{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_epinephrine",4},{"ACE_splint",2},{"ACE_tourniquet",4},{"OPTRE_M2_Smoke_Blue",2,1},{"OPTRE_M2_Smoke_Red",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_M9_Frag",2,1},{"OPTRE_12Rnd_127x40_Mag",2,12},{"ACE_painkillers",1,10},{"TCF_48Rnd_5x23mm_Mag_HV",8,48}}},{},"BDA_VX19_Helmet","",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","TFAR_microdagr",""}};

        ace_engineer = 2;
        ace_medical_MedicalClass = 1;

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };


    // HEROES OF BLACK DAGGER

    class B_BDA_Rib : B_BDA_SquadLead {
        editorPreview = "\BDA_Units\b_bdcunsc\data\preview\B_BDA_Rib.jpg";
        author = "Rib";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ribbington";
        side = 1;
        faction = "B_BDCUNSC";
        editorSubcategory = "BDA_ESC_HOBDC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "BDA_Uniform_B";

        linkedItems[] = {"BDA_Armor_Ribbington_v2","BDA_CH252D_Rib_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"BDA_Armor_Ribbington_v2","BDA_CH252D_Rib_Helmet","ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ACE_Altimeter"};

        weapons[] = {"OPTRE_BR55HB","OPTRE_M6C","BDA_Smartfinder"};
        respawnWeapons[] = {"OPTRE_BR55HB","OPTRE_M6C","BDA_Smartfinder"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag","TCF_12Rnd_127x40_Mag_NARQT","Laserbatteries","OPTRE_36Rnd_95x40_Mag","TCF_12Rnd_127x40_Mag_NARQT","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag","TCF_12Rnd_127x40_Mag_NARQT","Laserbatteries","OPTRE_36Rnd_95x40_Mag","TCF_12Rnd_127x40_Mag_NARQT","Laserbatteries"};

        backpack = "BDA_Naval_Belt_R";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_BR55HB","","","Optre_Recon_Sight_Green",{"OPTRE_36Rnd_95x40_Mag",36},{},""},{},{"OPTRE_M6C","","","",{"TCF_12Rnd_127x40_Mag_NARQT",12},{},""},{"BDA_Uniform_B",{{"ACE_elasticBandage",20},{"MineDetector",1},{"ACE_DefusalKit",1},{"ACE_EarPlugs",1},{"ACE_Chemlight_HiGreen",1,1}}},{"BDA_Armor_Ribbington_v2",{{"OPTRE_Biofoam",8},{"ToolKit",1},{"ACE_M26_Clacker",1},{"murshun_cigs_cigpack",2,20},{"murshun_cigs_lighter",1,100},{"TCF_12Rnd_127x40_Mag_NARQT",2,12},{"OPTRE_36Rnd_95x40_Mag",1,36}}},{"BDA_Naval_Belt_R",{{"ACE_EntrenchingTool",1},{"ItemcTabHCam",1},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_morphine",4},{"ACE_CableTie",3},{"ACE_epinephrine",2},{"ACE_IR_Strobe_Item",1},{"OPTRE_MA5Suppressor",1},{"OPTRE_M6C_compensator",1},{"OPTRE_M2_Smoke_Blue",2,1},{"OPTRE_M2_Smoke",3,1},{"OPTRE_M8_Flare_Green",2,1},{"OPTRE_M9_Frag",3,1},{"OPTRE_ELB47_Strobe",1,1},{"TCF_12Rnd_127x40_Mag_NARQT",2,12},{"OPTRE_36Rnd_95x40_Mag",10,36},{"TCF_36Rnd_95x40_Mag_JHP",5,36}}},"BDA_CH252D_Rib_Helmet","OPTRE_CBRN",{"BDA_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ACE_Altimeter",""}};

        ace_engineer = 2;
        ace_engineer_engineerclass = 2;
        ace_medical_MedicalClass = 2;
        ace_isEOD = 1;
        explosiveSpecialist = 1;

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};