//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.152100 on Stable branch
// Generated with ALiVE version 2.1.4.2408061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class BDA_RoseGarden_Fac {
        displayName = "Rose Garden Collective";
        side = 0;
        flag = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        icon = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class BDA_RoseGarden {
            name = "Rose Garden";

            class Infantry {
                name = "Infantry";

                class BDA_RoseGarden_infantry_fireteam {
                    name = "Fireteam";
                    side = 0;
                    faction = "BDA_RoseGarden";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Rifleman_AT_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Autoriflemen_01";
                    };
                };

                class BDA_RoseGarden_infantry_at_team {
                    name = "AT Team";
                    side = 0;
                    faction = "BDA_RoseGarden";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Rifleman_AT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Rifleman_AT_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Lasermen_01";
                    };
                };

                class BDA_RoseGarden_infantry_squad {
                    name = "Squad";
                    side = 0;
                    faction = "BDA_RoseGarden";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Rifleman_AT_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Autoriflemen_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Rifleman_AT_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Autoriflemen_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Marksman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_RTO_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Grenadier_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Lasermen_01";
                    };
                };

                class BDA_RoseGarden_infantry_breacher_team {
                    name = "Breacher Team";
                    side = 0;
                    faction = "BDA_RoseGarden";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Breacher_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Breacher_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Shield_Breacher_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Shield_Breacher_01";
                    };
                };

                class BDA_RoseGarden_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 0;
                    faction = "BDA_RoseGarden";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "BDA_RoseGarden__01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Marksman_01";
                    };
                };

                class BDA_RoseGarden_infantry_specialist_team {
                    name = "Specialist Team";
                    side = 0;
                    faction = "BDA_RoseGarden";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Lasermen_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Marksman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_Marksman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "BDA_RoseGarden_RTO_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LM_OPCAN_URA_Rifleman;
    class LM_OPCAN_URA_Rifleman_OCimport_01 : LM_OPCAN_URA_Rifleman { scope = 0; class EventHandlers; };
    class LM_OPCAN_URA_Rifleman_OCimport_02 : LM_OPCAN_URA_Rifleman_OCimport_01 { class EventHandlers; };

    class OPTRE_M12_LRV_ins;
    class OPTRE_M12_LRV_ins_OCimport_01 : OPTRE_M12_LRV_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_LRV_ins_OCimport_02 : OPTRE_M12_LRV_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M12R_AA_ins;
    class OPTRE_M12R_AA_ins_OCimport_01 : OPTRE_M12R_AA_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12R_AA_ins_OCimport_02 : OPTRE_M12R_AA_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M12_ins_APC;
    class OPTRE_M12_ins_APC_OCimport_01 : OPTRE_M12_ins_APC { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_ins_APC_OCimport_02 : OPTRE_M12_ins_APC_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
        };
    };

    class OPTRE_M12_VBIED;
    class OPTRE_M12_VBIED_OCimport_01 : OPTRE_M12_VBIED { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_VBIED_OCimport_02 : OPTRE_M12_VBIED_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
        };
    };

    class OPTRE_M12_TD_ins_IND;
    class OPTRE_M12_TD_ins_IND_OCimport_01 : OPTRE_M12_TD_ins_IND { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_TD_ins_IND_OCimport_02 : OPTRE_M12_TD_ins_IND_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_M494_INS;
    class OPTRE_M494_INS_OCimport_01 : OPTRE_M494_INS { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M494_INS_OCimport_02 : OPTRE_M494_INS_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_M808B_INS;
    class OPTRE_M808B_INS_OCimport_01 : OPTRE_M808B_INS { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M808B_INS_OCimport_02 : OPTRE_M808B_INS_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret1;
            class CargoTurret2;
            class CargoTurret3;
            class CargoTurret4;
            class CargoTurret5;
            class CargoTurret6;
            class CargoTurret7;
            class CargoTurret8;
        };
    };

    class OPTRE_UNSC_hornet_ins_IND;
    class OPTRE_UNSC_hornet_ins_IND_OCimport_01 : OPTRE_UNSC_hornet_ins_IND { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_UNSC_hornet_ins_IND_OCimport_02 : OPTRE_UNSC_hornet_ins_IND_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class OPTRE_Pelican_armed_70mm_ins;
    class OPTRE_Pelican_armed_70mm_ins_OCimport_01 : OPTRE_Pelican_armed_70mm_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Pelican_armed_70mm_ins_OCimport_02 : OPTRE_Pelican_armed_70mm_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class OPTRE_Static_FG75;
    class OPTRE_Static_FG75_OCimport_01 : OPTRE_Static_FG75 { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Static_FG75_OCimport_02 : OPTRE_Static_FG75_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_Static_M41_Ins;
    class OPTRE_Static_M41_Ins_OCimport_01 : OPTRE_Static_M41_Ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Static_M41_Ins_OCimport_02 : OPTRE_Static_M41_Ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_Static_AA_Ins_IND;
    class OPTRE_Static_AA_Ins_IND_OCimport_01 : OPTRE_Static_AA_Ins_IND { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Static_AA_Ins_IND_OCimport_02 : OPTRE_Static_AA_Ins_IND_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_ins_falcon_unarmed_IND;
    class OPTRE_ins_falcon_unarmed_IND_OCimport_01 : OPTRE_ins_falcon_unarmed_IND { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_ins_falcon_unarmed_IND_OCimport_02 : OPTRE_ins_falcon_unarmed_IND_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class LeftDoorGun;
            class RightDoorGun;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
        };
    };

    class optre_catfish_ins_mg_f;
    class optre_catfish_ins_mg_f_OCimport_01 : optre_catfish_ins_mg_f { scope = 0; class EventHandlers; class Turrets; };
    class optre_catfish_ins_mg_f_OCimport_02 : optre_catfish_ins_mg_f_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class MainTurret;
        };
    };

    class TCF_tarantula_02;
    class TCF_tarantula_02_OCimport_01 : TCF_tarantula_02 { scope = 0; class EventHandlers; class Turrets; };
    class TCF_tarantula_02_OCimport_02 : TCF_tarantula_02_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_AU_44_INS_Mortar;
    class OPTRE_AU_44_INS_Mortar_OCimport_01 : OPTRE_AU_44_INS_Mortar { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_AU_44_INS_Mortar_OCimport_02 : OPTRE_AU_44_INS_Mortar_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class TCF_Arkhangelsk_Koslovic;
    class TCF_Arkhangelsk_Koslovic_OCimport_01 : TCF_Arkhangelsk_Koslovic { scope = 0; class EventHandlers; class Turrets; };
    class TCF_Arkhangelsk_Koslovic_OCimport_02 : TCF_Arkhangelsk_Koslovic_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_m1015_mule_mlr_ins;
    class OPTRE_m1015_mule_mlr_ins_OCimport_01 : OPTRE_m1015_mule_mlr_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_m1015_mule_mlr_ins_OCimport_02 : OPTRE_m1015_mule_mlr_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };


    class BDA_RoseGarden_Rifleman_01 : LM_OPCAN_URA_Rifleman_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5B","TCF_M2311_D"};
        respawnWeapons[] = {"OPTRE_MA5B","TCF_M2311_D"};

        magazines[] = {"OPTRE_60Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "19thMD_Backpack_Standard";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","",{"OPTRE_60Rnd_762x51_Mag",60},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"Chemlight_green",2,1},{"OPTRE_60Rnd_762x51_Mag",3,60}}},{"19th_marine_vest_rifleman_Heavy_leg",{{"OPTRE_8Rnd_127x40_AP_Mag",5,8},{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1}}},{"19thMD_Backpack_Standard",{}},"OPTRE_FC_CH255_Helmet_URB_Visor","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_Autoriflemen_01 : BDA_RoseGarden_Rifleman_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autoriflemen";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M247","TCF_M2311_D","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M247","TCF_M2311_D","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_100Rnd_762x51_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_100Rnd_762x51_Box","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_100Rnd_762x51_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_100Rnd_762x51_Box","OPTRE_8Rnd_127x40_Mag"};

        backpack = "19thMD_Backpack_Standard_heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M247","","","OPTRE_BR55HB_Scope",{"OPTRE_100Rnd_762x51_Box",100},{},"bipod_01_F_blk"},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"19_CNML_HUR_T1A",1},{"Chemlight_green",2,1},{"OPTRE_100Rnd_762x51_Box",2,100}}},{"19th_marine_vest_rifleman_Heavy_leg",{{"OPTRE_8Rnd_127x40_AP_Mag",5,8},{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1},{"OPTRE_100Rnd_762x51_Box",4,100}}},{"19thMD_Backpack_Standard_heavy",{{"TCF_400Rnd_762x51_Box_APT",3,400}}},"OPTRE_FC_CH255_Helmet_URB_Visor","LM_OPCAN_UP_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_ins'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_ins";

    };

    class BDA_RoseGarden_Rifleman_AT_01 : BDA_RoseGarden_Rifleman_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5B","TCF_M57_Pilum_b","TCF_M2311_D","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5B","TCF_M57_Pilum_b","TCF_M2311_D","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_60Rnd_762x51_Mag","TCF_2Rnd_50x137_HEAT","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_762x51_Mag","TCF_2Rnd_50x137_HEAT","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "19thMD_Backpack_Standard_heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","",{"OPTRE_60Rnd_762x51_Mag",60},{},""},{"TCF_M57_Pilum_b","","","OPTRE_M392_Scope",{"TCF_2Rnd_50x137_HEAT",2},{},""},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"19_CNML_HUR_T1A",1},{"Chemlight_green",2,1},{"OPTRE_60Rnd_762x51_Mag",3,60}}},{"19th_marine_vest_rifleman_Heavy_leg",{{"OPTRE_8Rnd_127x40_AP_Mag",5,8},{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1},{"TCF_2Rnd_50x137_HEAT",2,2}}},{"19thMD_Backpack_Standard_heavy",{{"TCF_2Rnd_50x137_AA",2,2},{"TCF_2Rnd_50x137_GUIDED",4,2}}},"OPTRE_FC_CH255_Helmet_URB_Visor","LM_OPCAN_UP_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_ins'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_ins";

    };

    class BDA_RoseGarden_Marksman_01 : BDA_RoseGarden_Rifleman_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"19_UNSC_M392","TCF_M2311_D","OPTRE_Binoculars"};
        respawnWeapons[] = {"19_UNSC_M392","TCF_M2311_D","OPTRE_Binoculars"};

        magazines[] = {"15Rnd_762x51_M392","OPTRE_8Rnd_127x40_Mag","15Rnd_762x51_M392","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"15Rnd_762x51_M392","OPTRE_8Rnd_127x40_Mag","15Rnd_762x51_M392","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"19_UNSC_M392","","","19_UNSC_evosd",{"15Rnd_762x51_M392",15},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"19_CNML_HUR_T1A",1},{"Chemlight_green",2,1},{"15Rnd_762x51_M392",3,15}}},{"19th_marine_vest_rifleman_Heavy_leg",{{"OPTRE_8Rnd_127x40_AP_Mag",5,8},{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1},{"15Rnd_762x51_M392_AP",6,15}}},{},"OPTRE_FC_CH255_Helmet_URB_Visor","LM_OPCAN_UP_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_ins'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_ins";

    };

    class BDA_RoseGarden_Sniper_01 : BDA_RoseGarden_Marksman_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_rifleman_leg","OPTRE_FC_CH255_Helmet_URB","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_rifleman_leg","OPTRE_FC_CH255_Helmet_URB","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_SRM77_S2_Red","19_UNSC_M7_Side","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_SRM77_S2_Red","19_UNSC_M7_Side","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_10Rnd_127x99","60Rnd_5x23_m7_fmj","OPTRE_10Rnd_127x99","60Rnd_5x23_m7_fmj"};
        respawnMagazines[] = {"OPTRE_10Rnd_127x99","60Rnd_5x23_m7_fmj","OPTRE_10Rnd_127x99","60Rnd_5x23_m7_fmj"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRM77_S2_Red","","","OPTRE_SRS99C_Scope",{"OPTRE_10Rnd_127x99",10},{},""},{},{"19_UNSC_M7_Side","","","19_UNSC_M7_optic",{"60Rnd_5x23_m7_fmj",60},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"19_CNML_HUR_T1A",1},{"Chemlight_green",2,1},{"OPTRE_10Rnd_127x99",3,10},{"60Rnd_5x23_m7_fmj",3,60}}},{"19th_marine_vest_rifleman_leg",{{"OPTRE_10Rnd_127x99",7,10},{"60Rnd_5x23_m7_fmj",7,60}}},{},"OPTRE_FC_CH255_Helmet_URB","LM_OPCAN_UP_Shemagheye",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_ins'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_ins";

    };

    class BDA_RoseGarden_Breacher_01 : BDA_RoseGarden_Rifleman_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Breacher";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_breacher_heavy","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_breacher_heavy","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_CQS48S_Chihuahua_Automatic_Innie","TCF_M2311_D","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_CQS48S_Chihuahua_Automatic_Innie","TCF_M2311_D","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_12Rnd_12Gauge_Pellets_Tracer","OPTRE_8Rnd_127x40_Mag","OPTRE_12Rnd_12Gauge_Pellets_Tracer","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_12Rnd_12Gauge_Pellets_Tracer","OPTRE_8Rnd_127x40_Mag","OPTRE_12Rnd_12Gauge_Pellets_Tracer","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_CQS48S_Chihuahua_Automatic_Innie","","","",{"OPTRE_12Rnd_12Gauge_Pellets_Tracer",12},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"19_CNML_HUR_T1A",1},{"Chemlight_green",2,1},{"OPTRE_12Rnd_12Gauge_Pellets_Tracer",3,12}}},{"19th_marine_vest_breacher_heavy",{{"OPTRE_8Rnd_127x40_AP_Mag",5,8},{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1},{"OPTRE_12Rnd_12Gauge_Pellets",7,12}}},{},"OPTRE_FC_CH255_Helmet_URB_Visor","LM_OPCAN_UP_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_ins'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_ins";

    };

    class BDA_RoseGarden_RTO_01 : BDA_RoseGarden_Rifleman_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "RTO";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M7","TCF_M2311_D","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M7","TCF_M2311_D","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_ANPRC_521_URF";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","OPTRE_M7_Sight",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"19_CNML_HUR_T1A",1},{"Chemlight_green",2,1},{"OPTRE_60Rnd_5x23mm_Mag",3,60}}},{"19th_marine_vest_rifleman_Heavy_leg",{{"OPTRE_8Rnd_127x40_AP_Mag",5,8},{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1},{"OPTRE_60Rnd_5x23mm_Mag",8,60}}},{"OPTRE_ANPRC_521_URF",{}},"OPTRE_FC_CH255_Helmet_URB_Visor","LM_OPCAN_UP_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_ins'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_ins";

    };

    class BDA_RoseGarden_Shield_Breacher_01 : BDA_RoseGarden_Breacher_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Shield Breacher";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_breacher_heavy","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_breacher_heavy","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M7_Riot_Shield_Urban","TCF_M2311_D","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M7_Riot_Shield_Urban","TCF_M2311_D","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7_Riot_Shield_Urban","","","",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"19_CNML_HUR_T1A",1},{"Chemlight_green",2,1},{"OPTRE_60Rnd_5x23mm_Mag",3,60}}},{"19th_marine_vest_breacher_heavy",{{"OPTRE_8Rnd_127x40_AP_Mag",5,8},{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1},{"OPTRE_60Rnd_5x23mm_Mag",8,60}}},{},"OPTRE_FC_CH255_Helmet_URB_Visor","LM_OPCAN_UP_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_ins'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_ins";

    };

    class BDA_RoseGarden_Crewman_01 : BDA_RoseGarden_Rifleman_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "TCF_URA_Uni_URB";

        linkedItems[] = {"VES_M52A_URB_Vest_A","OPTRE_CH255_Security_Basic_Type_3_Helmet_Spartan_Black","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"VES_M52A_URB_Vest_A","OPTRE_CH255_Security_Basic_Type_3_Helmet_Spartan_Black","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M7","TCF_M2311_D","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M7","TCF_M2311_D","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"TCF_URA_Uni_URB",{{"FirstAidKit",1},{"19_CNML_HUR_T1A",1},{"Chemlight_green",2,1},{"OPTRE_60Rnd_5x23mm_Mag",3,60}}},{"VES_M52A_URB_Vest_A",{{"OPTRE_8Rnd_127x40_AP_Mag",5,8},{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1},{"OPTRE_60Rnd_5x23mm_Mag",8,60}}},{},"OPTRE_CH255_Security_Basic_Type_3_Helmet_Spartan_Black","LM_OPCAN_URB_UP_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_ins'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_ins";

    };

    class BDA_RoseGarden_Grenadier_01 : BDA_RoseGarden_Rifleman_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M319","19_UNSC_M7_Side","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M319","19_UNSC_M7_Side","OPTRE_Binoculars"};

        magazines[] = {"TCF_UGL_8Gauge_Pellet","60Rnd_5x23_m7_fmj","TCF_UGL_8Gauge_Pellet","60Rnd_5x23_m7_fmj"};
        respawnMagazines[] = {"TCF_UGL_8Gauge_Pellet","60Rnd_5x23_m7_fmj","TCF_UGL_8Gauge_Pellet","60Rnd_5x23_m7_fmj"};

        backpack = "19thMD_Backpack_Standard_heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M319","","","",{"TCF_UGL_8Gauge_Pellet",1},{},""},{},{"19_UNSC_M7_Side","","","19_UNSC_M7_optic",{"60Rnd_5x23_m7_fmj",60},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"19_CNML_HUR_T1A",1},{"Chemlight_green",2,1},{"TCF_UGL_8Gauge_Pellet",3,1},{"60Rnd_5x23_m7_fmj",3,60}}},{"19th_marine_vest_rifleman_Heavy_leg",{{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1},{"60Rnd_5x23_m7_fmj",4,60},{"1Rnd_HE_Grenade_shell",8,1}}},{"19thMD_Backpack_Standard_heavy",{}},"OPTRE_FC_CH255_Helmet_URB_Visor","LM_OPCAN_UP_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_ins'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_ins";

    };

    class BDA_RoseGarden_Warthog_01 : OPTRE_M12_LRV_ins_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "MG Warthog";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Rifleman_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\Warthog\data\ins\M12HogMaav_extupper_innie2_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\Warthog\data\night\M12HogMaav_extunder_night_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles\Warthog\data\ins\m12_turret_ins3_co.paa'];_unit setObjectTextureGlobal [3,'\OPTRE_Vehicles\warthog\data\decals_ca.paa'];_unit setObjectTextureGlobal [4,'\OPTRE_Vehicles\warthog\data\m12hogmaav_interior_co.paa'];_unit setObjectTextureGlobal [5,'\OPTRE_Vehicles\warthog\data\turrets\m12_turret_decals_ca.paa'];_unit setObjectTextureGlobal [6,'\OPTRE_Vehicles\warthog\data\turrets\sight_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Innie";

    };

    class BDA_RoseGarden_AA_Warthog_01 : OPTRE_M12R_AA_ins_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "AA Warthog";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Rifleman_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "BDA_RoseGarden_Autoriflemen_01"; };
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_APC_Warthog_01 : OPTRE_M12_ins_APC_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "APC Warthog";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Rifleman_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "BDA_RoseGarden_Autoriflemen_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "OPTRE_Ins_URF_Autorifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_VBIED_01 : OPTRE_M12_VBIED_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "VBIED";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Rifleman_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_TD_Warthog_01 : OPTRE_M12_TD_ins_IND_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "TD Warthog";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Rifleman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_Oryx_IFV_01 : OPTRE_M494_INS_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Oryx IFV";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_Scorpion_01 : OPTRE_M808B_INS_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Scorpion";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Crewman_01"; };
            class CargoTurret1 : CargoTurret1 { gunnerType = ""; };
            class CargoTurret2 : CargoTurret2 { gunnerType = ""; };
            class CargoTurret3 : CargoTurret3 { gunnerType = ""; };
            class CargoTurret4 : CargoTurret4 { gunnerType = ""; };
            class CargoTurret5 : CargoTurret5 { gunnerType = ""; };
            class CargoTurret6 : CargoTurret6 { gunnerType = ""; };
            class CargoTurret7 : CargoTurret7 { gunnerType = ""; };
            class CargoTurret8 : CargoTurret8 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_Hornet_01 : OPTRE_UNSC_hornet_ins_IND_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hornet";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Crewman_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "BDA_RoseGarden_Autoriflemen_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "BDA_RoseGarden_Autoriflemen_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles_Air\hornet\data\hornet_hull_innie2_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorinnie2";

    };

    class BDA_RoseGarden_Pelican_01 : OPTRE_Pelican_armed_70mm_ins_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pelican";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Crewman_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "BDA_RoseGarden_Crewman_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Pelican\data\PelicanExterior_innie_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorinnie";

    };

    class BDA_RoseGarden_Field_Gun_01 : OPTRE_Static_FG75_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Field Gun";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "OPTRE_Ins_URF_Engineer";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_MG_Turret_01 : OPTRE_Static_M41_Ins_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "MG Turret";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "OPTRE_Ins_URF_Rifleman_AR";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_AA_Turret_01 : OPTRE_Static_AA_Ins_IND_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "AA Turret";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "OPTRE_Ins_URF_Rifleman_AR";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_Falcon_01 : OPTRE_ins_falcon_unarmed_IND_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Falcon";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Crewman_01";

        class Turrets : Turrets {
            class LeftDoorGun : LeftDoorGun { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
            class RightDoorGun : RightDoorGun { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_MG_Boat_01 : optre_catfish_ins_mg_f_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "MG Boat";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Rifleman_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_Tarantula_AA_01 : TCF_tarantula_02_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Tarantula AA";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_AU_44_01 : OPTRE_AU_44_INS_Mortar_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "AU-44";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "OPTRE_Ins_URF_Rifleman_AR";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_M400_Arkhangelsk_01 : TCF_Arkhangelsk_Koslovic_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "M400 Arkhangelsk";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'TCF_OPFOR\Koslovic\Vehicles\data\MBT_02_body_Koslovic_CO.paa'];_unit setObjectTextureGlobal [1,'TCF_OPFOR\Koslovic\Vehicles\data\MBT_02_scorcher_Koslovic_CO.paa'];_unit setObjectTextureGlobal [2,'TCF_OPFOR\Koslovic\Vehicles\data\MBT_02_Koslovic_CO.paa'];_unit setObjectTextureGlobal [3,'TCF_OPFOR\Koslovic\Vehicles\data\Turret_Koslovic_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "KOS_Regular";

    };

    class BDA_RoseGarden_M1015_Mule_01 : OPTRE_m1015_mule_mlr_ins_OCimport_02 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "M1015 Mule";
        side = 0;
        faction = "BDA_RoseGarden";
        crew = "BDA_RoseGarden_Rifleman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "BDA_RoseGarden_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_Team_Leader_01 : BDA_RoseGarden_Rifleman_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5CGL","TCF_M96_LAW_Blk","TCF_M2311_D"};
        respawnWeapons[] = {"OPTRE_MA5CGL","TCF_M96_LAW_Blk","TCF_M2311_D"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag"};

        backpack = "19thMD_Backpack_Standard_rto";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5CGL","","","",{"OPTRE_32Rnd_762x51_Mag",32},{"1Rnd_HE_Grenade_shell",1},""},{"TCF_M96_LAW_Blk","","","",{},{},""},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"Chemlight_green",2,1},{"OPTRE_32Rnd_762x51_Mag",3,32},{"1Rnd_HE_Grenade_shell",3,1}}},{"19th_marine_vest_rifleman_Heavy_leg",{{"OPTRE_8Rnd_127x40_AP_Mag",5,8},{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1},{"OPTRE_32Rnd_762x51_Mag",7,32},{"1Rnd_HE_Grenade_shell",5,1}}},{"19thMD_Backpack_Standard_rto",{}},"OPTRE_FC_CH255_Helmet_URB_Visor","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class BDA_RoseGarden_Lasermen_01 : BDA_RoseGarden_Rifleman_01 {
        author = "CPO. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Lasermen";
        side = 0;
        faction = "BDA_RoseGarden";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "19thu_U_Insurgent";

        linkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"19th_marine_vest_rifleman_Heavy_leg","OPTRE_FC_CH255_Helmet_URB_Visor","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA37K","OPTRE_M6GGNR","TCF_M2311_D"};
        respawnWeapons[] = {"OPTRE_MA37K","OPTRE_M6GGNR","TCF_M2311_D"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_SpLaser_Battery_Launcher","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_SpLaser_Battery_Launcher","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "19thMD_Backpack_Standard_heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37K","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"OPTRE_M6GGNR","","","",{"OPTRE_SpLaser_Battery_Launcher",4},{},""},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"19thu_U_Insurgent",{{"FirstAidKit",1},{"Chemlight_green",2,1},{"OPTRE_32Rnd_762x51_Mag",3,32}}},{"19th_marine_vest_rifleman_Heavy_leg",{{"OPTRE_8Rnd_127x40_AP_Mag",5,8},{"OPTRE_M9_Frag",3,1},{"ACE_M84",3,1},{"OPTRE_32Rnd_762x51_Mag",6,32}}},{"19thMD_Backpack_Standard_heavy",{{"OPTRE_SpLaser_Battery_Launcher",1,4}}},"OPTRE_FC_CH255_Helmet_URB_Visor","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};