class CfgPatches {
    class I_ADS_DES {
        units[] = {
            "I_ADS_Rifleman_MA40_DES",
            "I_ADS_Rifleman_Commando_DES",
            "I_ADS_Rifleman_M7_DES",
            "I_ADS_Rifleman_M45_DES",
            "I_ADS_AutoRifleman_DES",
            "I_ADS_Marksman_BR55_DES",
            "I_ADS_Marksman_DMR_DES",
            "I_ADS_Grenadier_MA40_DES",
            "I_ADS_Grenadier_HMG_38_DES",
            "I_ADS_Demolitionist_DES",
            "I_ADS_Heavy_DES",
            "I_ADS_Sniper_DES",
            "I_ADS_Medic_DES",
            "I_ADS_Team_Leader_DES",
            "I_ADS_Squad_Leader_DES",
            "I_ADS_Officer_DES",
            "I_ADS_Pilot_DES",
            "I_ADS_Air_Crewman_DES",
            "I_ADS_Crewman_DES",
            "I_ADS_Recon_Rifleman_DES",
            "I_ADS_Recon_Marksman_DES",
            "I_ADS_Recon_AutoRifleman_DES",
            "I_ADS_Recon_Grenadier_DES",
            "I_ADS_Recon_Heavy_DES",
            "I_ADS_Recon_Medic_DES",
            "I_ADS_Recon_Sniper_DES",
            "I_ADS_Recon_Team_Leader_DES",
            "I_ADS_Recon_Squad_Leader_DES",
            "I_ADS_M412_Bison_IFV_DES",
            "I_ADS_M413_Bison_MGS_DES",
            "I_ADS_M494_Oryx_IFV_DES",
            "I_ADS_M808S_Scorpion_MBT_DES",
            "I_ADS_M12_FAV_DES",
            "I_ADS_M12_LRV_DES_MG",
            "I_ADS_M12A1_LRV_DES_ATGM",
            "I_ADS_M12R_LRV_DES_AA",
            "I_ADS_M831_Troop_Transport_DES",
            "I_ADS_HDV_134_Buffalo_DES",
            "I_ADS_HDV_134_Buffalo_DES_Ammo",
            "I_ADS_HDV_134_Buffalo_DES_Device",
            "I_ADS_HDV_134_Buffalo_DES_Fuel",
            "I_ADS_HDV_134_Buffalo_DES_Covered",
            "I_ADS_Mk6_Mortar_DES",
            "I_ADS_M41_LAAG_Turret_DES",
            "I_ADS_M79_AA_Turret_DES",
            "I_ADS_FG75_Anti_Tank_Gun_DES",
            "I_ADS_M71_Scythe_AA_DES",
            "I_ADS_M95_Lance_DES",
            "I_ADS_MQ_221_Dragonfly_DES",
            "I_ADS_F99_Wombat_DES",
            "I_ADS_Demining_Drone_DES",
            "I_ADS_D77H_TCI_AV_SOCOM_Pelican_DES",
            "I_ADS_UH_144S_Falcon_DES_Armed",
            "I_ADS_UH_144S_Falcon_DES_Unarmed",
            "I_ADS_AV_22_Sparrowhawk_DES",
            "I_ADS_AV_22L_Sparrowhawk_DES"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        author = "Sgt. N. Knight";
        authors[] = {"Sgt. N. Knight"};
    };
};
