[  
 UNSC_Ari_2,             
 "Escort to Arizona Sword CIC",            
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",      
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",    
 "_this distance _target < 10",        
 "_caller distance _target < 10",        
 {},  
 {},  
 { player setPosATL (getPosATL UNSC_CIC_TP) },  
 {},  
 [],  
 1,  
 0,  
 false,  
 false  
] call BIS_fnc_holdActionAdd;
[  
 UNSC_Ari_2,             
 "Escort to Barracks",            
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",      
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",    
 "_this distance _target < 10",        
 "_caller distance _target < 10",        
 {},  
 {},  
 { player setPosATL (getPosATL UNSC_Crew) },  
 {},  
 [],  
 1,  
 0,  
 false,  
 false  
] call BIS_fnc_holdActionAdd;
[  
 UNSC_Ari_2,             
 "Escort to Podbay 1",            
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",      
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",    
 "_this distance _target < 10",        
 "_caller distance _target < 10",        
 {},  
 {},  
 { player setPosATL (getPosATL UNSC_Pod_1) },  
 {},  
 [],  
 1,  
 0,  
 false,  
 false  
] call BIS_fnc_holdActionAdd;
[  
 UNSC_Ari_2,             
 "Escort to Podbay 2",            
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",      
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",    
 "_this distance _target < 10",        
 "_caller distance _target < 10",        
 {},  
 {},  
 { player setPosATL (getPosATL UNSC_Pod_2) },  
 {},  
 [],  
 1,  
 0,  
 false,  
 false  
] call BIS_fnc_holdActionAdd;
[  
 UNSC_Ari_2,             
 "Escort to Bridge",            
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",      
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",    
 "_this distance _target < 10",        
 "_caller distance _target < 10",        
 {},  
 {},  
 { player setPosATL (getPosATL UNSC_Bridge_2) },  
 {},  
 [],  
 1,  
 0,  
 false,  
 false  
] call BIS_fnc_holdActionAdd;
[  
 UNSC_Ari_2,             
 "Escort to NCO Room",            
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",      
 "BDA_Core\BDA_UI\holdAction\holdAction_transport_ca.paa",    
 "_this distance _target < 10",        
 "_caller distance _target < 10",        
 {},  
 {},  
 { player setPosATL (getPosATL UNSC_Soldier_2) },  
 {},  
 [],  
 1,  
 0,  
 false,  
 false  
] call BIS_fnc_holdActionAdd;