class CfgPatches {
    class I_ADS {
        units[] = {
            "I_ADS_Rifleman_MA40",
            "I_ADS_Rifleman_M7",
            "I_ADS_Rifleman_Commando",
            "I_ADS_Rifleman_M45",
            "I_ADS_Marksman_BR55",
            "I_ADS_Marksman_DMR",
            "I_ADS_Grenadier_MA40",
            "I_ADS_Grenadier_HMG_38",
            "I_ADS_AutoRifleman",
            "I_ADS_Demolistionist",
            "I_ADS_Heavy",
            "I_ADS_Sniper",
            "I_ADS_Medic",
            "I_ADS_Team_Leader",
            "I_ADS_Squad_Leader",
            "I_ADS_Officer",
            "I_ADS_Pilot",
            "I_ADS_Air_Crewman",
            "I_ADS_Crewman",
            "I_ADS_Rifleman_Scout_01",
            "I_ADS_Recon_Squad_Leader",
            "I_ADS_M494_Oryx_IFV",
            "I_ADS_M412_Bison_IFV",
            "I_ADS_M413_Bison_MGS",
            "I_ADS_D77H_TCI_SOCOM_Pelican",
            "I_ADS_M808S_Scorpion_MBT_01",
            "I_ADS_UH_144S_Falcon_Unarmed_01",
            "I_ADS_F99_Wombat_01",
            "I_ADS_Recon_Heavy",
            "I_ADS_M112_Wet_Patrol_Craft_MG",
            "I_ADS_M112_Wet_Patrol_Craft_AA",
            "I_ADS_M71_Scythe_AA",
            "I_ADS_M95_Lance",
            "I_ADS_M41_LAAG_Turret",
            "I_ADS_M79_AA_Turret",
            "I_ADS_FG75_Anti_Tank_Gun",
            "I_ADS_Mk6_Mortar",
            "I_ADS_Demining_Drone",
            "I_ADS_MQ_221_Dragonfly",
            "I_ADS_UH_144S_Falcon_Armed_01",
            "I_ADS_M12_FAV",
            "I_ADS_M12_LRV_MG",
            "I_ADS_M12A1_LRV_ATGM",
            "I_ADS_M831_Troop_Transport",
            "I_ADS_M12R_LRV_AA",
            "I_ADS_AV_22_Sparrowhawk_01",
            "I_ADS_AV_22L_Sparrowhawk_01",
            "I_ADS_Recon_Team_Leader",
            "I_ADS_Recon_Sniper",
            "I_ADS_Recon_Medic",
            "I_ADS_Recon_Grenadier",
            "I_ADS_Recon_Autorifleman",
            "I_ADS_Recon_Marksman",
            "I_ADS_HDV_134_Buffalo_Ammo",
            "I_ADS_HDV_134_Buffalo_Device",
            "I_ADS_HDV_134_Buffalo_Fuel",
            "I_ADS_HDV_134_Buffalo",
            "I_ADS_HDV_134_Buffalo_Covered"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        author = "Sgt. N. Knight";
        authors[] = {"Sgt. N. Knight"};
    };
};
