//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152405 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_1ITA {
        displayName = "1st Independent Tank Army";
        side = 0;
        flag = "\BDA_1ITA\1ITA_FLAG.paa";
        icon = "\BDA_1ITA\1ITA_FLAG.paa";
        priority = 0;
    };
};
