class CfgPatches {
    class I_ADS_WDL {
        units[] = {
            "I_ADS_Crewman_WDL",
            "I_ADS_Rifleman_MA40_WDL",
            "I_ADS_Rifleman_Commando_WDL",
            "I_ADS_Rifleman_M7_WDL",
            "I_ADS_Rifleman_M45_WDL",
            "I_ADS_Marksman_BR55_WDL",
            "I_ADS_Marksman_DMR_WDL",
            "I_ADS_Grenadier_MA40_WDL",
            "I_ADS_Grenadier_HMG_38_WDL",
            "I_ADS_AutoRifleman_WDL",
            "I_ADS_Demolitionist_WDL",
            "I_ADS_Heavy_WDL",
            "I_ADS_Sniper_WDL",
            "I_ADS_Medic_WDL",
            "I_ADS_Team_Leader_WDL",
            "I_ADS_Squad_Leader_WDL",
            "I_ADS_Officer_WDL",
            "I_ADS_Pilot_WDL",
            "I_ADS_Air_Crewman_WDL",
            "I_ADS_Recon_Rifleman_WDL",
            "I_ADS_Recon_Marksman_WDL",
            "I_ADS_Recon_AutoRifleman_WDL",
            "I_ADS_Recon_Grenadier_WDL",
            "I_ADS_Recon_Heavy_WDL",
            "I_ADS_Recon_Sniper_WDL",
            "I_ADS_Recon_Medic_WDL",
            "I_ADS_Recon_Team_Leader_WDL",
            "I_ADS_Recon_Squad_Leader_WDL",
            "I_ADSWDL_M412_Bison_IFV_WDL_01",
            "I_ADSWDL_M413_Bison_MGS_WDL",
            "I_ADSWDL_M494_Oryx_IFV_WDL",
            "I_ADSWDL_M808S_Scorpion_MBT_WDL",
            "I_ADSWDL_M12_FAV_WDL",
            "I_ADSWDL_M12_LRV_WDL_MG",
            "I_ADSWDL_M12A1_LRV_WDL_ATGM",
            "I_ADSWDL_M12R_LRV_WDL_AA",
            "I_ADSWDL_M831_Troop_Transport_WDL",
            "I_ADSWDL_HDV_134_Buffalo_WDL",
            "I_ADSWDL_HDV_134_Buffalo_WDL_Ammo",
            "I_ADSWDL_HDV_134_Buffalo_WDL_Device",
            "I_ADSWDL_HDV_134_Buffalo_WDL_Fuel",
            "I_ADSWDL_HDV_134_Buffalo_WDL_Covered",
            "I_ADSWDL_Mk6_Mortar",
            "I_ADSWDL_M41_LAAG_Turret",
            "I_ADSWDL_M79_AA_Turret",
            "I_ADSWDL_FG75_Anti_Tank_Gun",
            "I_ADSWDL_M71_Scythe_AA",
            "I_ADSWDL_M95_Lance",
            "I_ADSWDL_M112_Wet_Patrol_Craft_MG",
            "I_ADSWDL_M112_Wet_Patrol_Craft_AA",
            "I_ADSWDL_MQ_221_Dragonfly_WDL",
            "I_ADSWDL_F99_Wombat_WDL",
            "I_ADSWDL_Demining_Drone",
            "I_ADSWDL_D77H_TCI_AV_SOCOM_Pelican",
            "I_ADSWDL_UH_144S_Falcon_WDL_Armed",
            "I_ADSWDL_UH_144S_Falcon_WDL_Unarmed",
            "I_ADSWDL_AV_22_Sparrowhawk_WDL",
            "I_ADSWDL_AV_22L_Sparrowhawk_WDL"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        author = "Sgt. N. Knight";
        authors[] = {"Sgt. N. Knight"};
    };
};
