//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151931 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_CovenantEmpire {
        displayName = "Crimson Sons";
        side = 1;
        flag = "";
        icon = "";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        class B_CovenantEmpire {
            name = "Crimson Sons";

            class Infantry {
                name = "Infantry";

                class b_covenant_empire_infantry_hunter_pair {
                    name = "Hunter Pair";
                    side = 1;
                    faction = "B_CovenantEmpire";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Hunter_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Hunter_01";
                    };
                };

                class b_covenant_empire_infantry_elite_fireteam {
                    name = "Elite Fireteam";
                    side = 1;
                    faction = "B_CovenantEmpire";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Officer_01";
                    };
                    class Unit1 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Minor_01";
                    };
                    class Unit2 {
                        position[] = {-5,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_AT_01";
                    };
                    class Unit3 {
                        position[] = {10,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Marksman_01";
                    };
                };

                class b_covenant_empire_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 1;
                    faction = "B_CovenantEmpire";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Jackal_Sniper_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Jackal_Marksman_01";
                    };
                };

                class b_covenant_empire_infantry_crimson_section {
                    name = "Crimson Section";
                    side = 1;
                    faction = "B_CovenantEmpire";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Minor_WBK_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Grunt_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Grunt_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Grunt_01";
                    };
                };

                class b_covenant_empire_infantry_jackal_fireteam {
                    name = "Jackal Fireteam";
                    side = 1;
                    faction = "B_CovenantEmpire";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Jackal_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Jackal_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Jackal_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Jackal_01";
                    };
                };

                class b_covenant_empire_infantry_elite_squad {
                    name = "Elite Squad";
                    side = 1;
                    faction = "B_CovenantEmpire";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Major_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Officer_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Minor_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Minor_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Minor_01";
                    };
                    class Unit5 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_AT_01";
                    };
                    class Unit6 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Marksman_01";
                    };
                    class Unit7 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Covenant_Empire_Crimson_Elite_Marksman_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class OPTRE_FC_Elite_Major;
    class OPTRE_FC_Elite_Major_OCimport_01 : OPTRE_FC_Elite_Major { scope = 0; class EventHandlers; };
    class OPTRE_FC_Elite_Major_OCimport_02 : OPTRE_FC_Elite_Major_OCimport_01 { class EventHandlers; };

    class OPTRE_FC_Elite_Officer;
    class OPTRE_FC_Elite_Officer_OCimport_01 : OPTRE_FC_Elite_Officer { scope = 0; class EventHandlers; };
    class OPTRE_FC_Elite_Officer_OCimport_02 : OPTRE_FC_Elite_Officer_OCimport_01 { class EventHandlers; };

    class OPTRE_FC_Elite_Zealot;
    class OPTRE_FC_Elite_Zealot_OCimport_01 : OPTRE_FC_Elite_Zealot { scope = 0; class EventHandlers; };
    class OPTRE_FC_Elite_Zealot_OCimport_02 : OPTRE_FC_Elite_Zealot_OCimport_01 { class EventHandlers; };

    class OPTRE_FC_Elite_MinorAT;
    class OPTRE_FC_Elite_MinorAT_OCimport_01 : OPTRE_FC_Elite_MinorAT { scope = 0; class EventHandlers; };
    class OPTRE_FC_Elite_MinorAT_OCimport_02 : OPTRE_FC_Elite_MinorAT_OCimport_01 { class EventHandlers; };

    class WBK_EliteMainWeap_3;
    class WBK_EliteMainWeap_3_OCimport_01 : WBK_EliteMainWeap_3 { scope = 0; class EventHandlers; };
    class WBK_EliteMainWeap_3_OCimport_02 : WBK_EliteMainWeap_3_OCimport_01 { class EventHandlers; };

    class WBK_EliteMainWeap_6;
    class WBK_EliteMainWeap_6_OCimport_01 : WBK_EliteMainWeap_6 { scope = 0; class EventHandlers; };
    class WBK_EliteMainWeap_6_OCimport_02 : WBK_EliteMainWeap_6_OCimport_01 { class EventHandlers; };

    class WBK_HaloHunter_2;
    class WBK_HaloHunter_2_OCimport_01 : WBK_HaloHunter_2 { scope = 0; class EventHandlers; };
    class WBK_HaloHunter_2_OCimport_02 : WBK_HaloHunter_2_OCimport_01 { class EventHandlers; };

    class OPTRE_Jackal_F;
    class OPTRE_Jackal_F_OCimport_01 : OPTRE_Jackal_F { scope = 0; class EventHandlers; };
    class OPTRE_Jackal_F_OCimport_02 : OPTRE_Jackal_F_OCimport_01 { class EventHandlers; };

    class OPTRE_Jackal_Sniper_F_IND;
    class OPTRE_Jackal_Sniper_F_IND_OCimport_01 : OPTRE_Jackal_Sniper_F_IND { scope = 0; class EventHandlers; };
    class OPTRE_Jackal_Sniper_F_IND_OCimport_02 : OPTRE_Jackal_Sniper_F_IND_OCimport_01 { class EventHandlers; };

    class OPTRE_Jackal_Sharpshooter_F_IND;
    class OPTRE_Jackal_Sharpshooter_F_IND_OCimport_01 : OPTRE_Jackal_Sharpshooter_F_IND { scope = 0; class EventHandlers; };
    class OPTRE_Jackal_Sharpshooter_F_IND_OCimport_02 : OPTRE_Jackal_Sharpshooter_F_IND_OCimport_01 { class EventHandlers; };

    class WBK_Grunt_2;
    class WBK_Grunt_2_OCimport_01 : WBK_Grunt_2 { scope = 0; class EventHandlers; };
    class WBK_Grunt_2_OCimport_02 : WBK_Grunt_2_OCimport_01 { class EventHandlers; };

    class OPTRE_FC_Wraith_IND;
    class OPTRE_FC_Wraith_IND_OCimport_01 : OPTRE_FC_Wraith_IND { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_Wraith_IND_OCimport_02 : OPTRE_FC_Wraith_IND_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_FC_Spectre_AI;
    class OPTRE_FC_Spectre_AI_OCimport_01 : OPTRE_FC_Spectre_AI { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_Spectre_AI_OCimport_02 : OPTRE_FC_Spectre_AI_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret1;
            class CargoTurret2;
            class MainTurret;
        };
    };

    class OPTRE_FC_Spectre_AT;
    class OPTRE_FC_Spectre_AT_OCimport_01 : OPTRE_FC_Spectre_AT { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_Spectre_AT_OCimport_02 : OPTRE_FC_Spectre_AT_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret1;
            class CargoTurret2;
            class MainTurret;
        };
    };

    class OPTRE_FC_Type27_Banshee;
    class OPTRE_FC_Type27_Banshee_OCimport_01 : OPTRE_FC_Type27_Banshee { scope = 0; class EventHandlers; };
    class OPTRE_FC_Type27_Banshee_OCimport_02 : OPTRE_FC_Type27_Banshee_OCimport_01 { scope = 0; class EventHandlers; };

    class OPTRE_FC_Spirit;
    class OPTRE_FC_Spirit_OCimport_01 : OPTRE_FC_Spirit { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_Spirit_OCimport_02 : OPTRE_FC_Spirit_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class CargoTurret_10;
            class CargoTurret_11;
            class CargoTurret_12;
            class CargoTurret_13;
            class CargoTurret_14;
            class CargoTurret_15;
            class CargoTurret_16;
        };
    };


    class B_Covenant_Empire_Crimson_Elite_Minor_01 : OPTRE_FC_Elite_Major_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Elite Minor";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"Elite03SNG"};

        uniformClass = "OPTRE_FC_Elite_CombatSkin";

        linkedItems[] = {"OPTRE_FC_Elite_Armor_Major","OPTRE_FC_Elite_Helmet_Major","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_FC_Elite_Armor_Major","OPTRE_FC_Elite_Helmet_Major","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_FC_T51J_Repeater"};
        respawnWeapons[] = {"OPTRE_FC_T51J_Repeater"};

        magazines[] = {"OPTRE_FC_T51J_Repeater_Battery","OPTRE_FC_T51J_Repeater_Battery"};
        respawnMagazines[] = {"OPTRE_FC_T51J_Repeater_Battery","OPTRE_FC_T51J_Repeater_Battery"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T51J_Repeater","","","",{"OPTRE_FC_T51J_Repeater_Battery",300},{},""},{},{},{"OPTRE_FC_Elite_CombatSkin",{{"FirstAidKit",1},{"OPTRE_FC_NVG",1},{"OPTRE_FC_PlasmaGrenade",2,1},{"OPTRE_FC_T51J_Repeater_Battery",3,300}}},{"OPTRE_FC_Elite_Armor_Major",{{"OPTRE_FC_T51J_Repeater_Battery",4,300}}},{},"OPTRE_FC_Elite_Helmet_Major","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Elite_Officer_01 : OPTRE_FC_Elite_Officer_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Elite Officer";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"Elite03SNG"};

        uniformClass = "OPTRE_FC_Elite_CombatSkin";

        linkedItems[] = {"OPTRE_FC_Elite_Armor_Officer","OPTRE_FC_Elite_Helmet_Officer","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_FC_Elite_Armor_Officer","OPTRE_FC_Elite_Helmet_Officer","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_FC_T51J_Repeater"};
        respawnWeapons[] = {"OPTRE_FC_T51J_Repeater"};

        magazines[] = {"OPTRE_FC_T51J_Repeater_Battery","OPTRE_FC_T51J_Repeater_Battery"};
        respawnMagazines[] = {"OPTRE_FC_T51J_Repeater_Battery","OPTRE_FC_T51J_Repeater_Battery"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T51J_Repeater","","","",{"OPTRE_FC_T51J_Repeater_Battery",300},{},""},{},{},{"OPTRE_FC_Elite_CombatSkin",{{"FirstAidKit",1},{"OPTRE_FC_NVG",1},{"OPTRE_FC_PlasmaGrenade",1,1},{"OPTRE_FC_T51J_Repeater_Battery",3,300}}},{"OPTRE_FC_Elite_Armor_Officer",{{"OPTRE_FC_T51J_Repeater_Battery",4,300}}},{},"OPTRE_FC_Elite_Helmet_Officer","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Elite_Major_01 : OPTRE_FC_Elite_Zealot_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Elite Major";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"Elite03SNG"};

        uniformClass = "OPTRE_FC_Elite_CombatSkin";

        linkedItems[] = {"OPTRE_FC_Elite_Armor_Zealot","OPTRE_FC_Elite_Helmet_Zealot","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_FC_Elite_Armor_Zealot","OPTRE_FC_Elite_Helmet_Zealot","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_FC_T50_ConcussionRifle"};
        respawnWeapons[] = {"OPTRE_FC_T50_ConcussionRifle"};

        magazines[] = {"OPTRE_FC_T50_6rnd_mag","OPTRE_FC_T50_6rnd_mag"};
        respawnMagazines[] = {"OPTRE_FC_T50_6rnd_mag","OPTRE_FC_T50_6rnd_mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T50_ConcussionRifle","","","",{"OPTRE_FC_T50_6rnd_mag",6},{},""},{},{},{"OPTRE_FC_Elite_CombatSkin",{{"FirstAidKit",1},{"OPTRE_FC_NVG",1},{"OPTRE_FC_T50_6rnd_mag",3,6}}},{"OPTRE_FC_Elite_Armor_Zealot",{{"OPTRE_FC_T50_6rnd_mag",4,6}}},{},"OPTRE_FC_Elite_Helmet_Zealot","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Elite_AT_01 : OPTRE_FC_Elite_MinorAT_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Elite (AT)";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"Elite03SNG"};

        uniformClass = "OPTRE_FC_Elite_CombatSkin";

        linkedItems[] = {"OPTRE_FC_Elite_Armor_Major","OPTRE_FC_Elite_Helmet_Major","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_FC_Elite_Armor_Major","OPTRE_FC_Elite_Helmet_Major","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_FC_T25J_Rifle","OPTRE_FC_T33_FuelRod_Cannon"};
        respawnWeapons[] = {"OPTRE_FC_T25J_Rifle","OPTRE_FC_T33_FuelRod_Cannon"};

        magazines[] = {"OPTRE_FC_T25J_Rifle_Battery","OPTRE_FC_T33_FuelRod_Pack","OPTRE_FC_T25J_Rifle_Battery"};
        respawnMagazines[] = {"OPTRE_FC_T25J_Rifle_Battery","OPTRE_FC_T33_FuelRod_Pack","OPTRE_FC_T25J_Rifle_Battery"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T25J_Rifle","","","",{"OPTRE_FC_T25J_Rifle_Battery",200},{},""},{"OPTRE_FC_T33_FuelRod_Cannon","","","",{"OPTRE_FC_T33_FuelRod_Pack",5},{},""},{},{"OPTRE_FC_Elite_CombatSkin",{{"FirstAidKit",1},{"OPTRE_FC_NVG",1},{"OPTRE_FC_T33_FuelRod_Pack",2,5},{"OPTRE_FC_T25J_Rifle_Battery",6,200}}},{"OPTRE_FC_Elite_Armor_Major",{}},{},"OPTRE_FC_Elite_Helmet_Major","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Elite_Minor_WBK_01 : WBK_EliteMainWeap_3_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Elite Minor (WBK)";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"Elite03SNG"};

        uniformClass = "OPTRE_FC_Elite_CombatSkin";

        linkedItems[] = {"OPTRE_FC_Elite_Armor_Major","OPTRE_FC_Elite_Helmet_Major","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_FC_NVG"};
        respawnlinkedItems[] = {"OPTRE_FC_Elite_Armor_Major","OPTRE_FC_Elite_Helmet_Major","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_FC_NVG"};

        weapons[] = {"OPTRE_FC_T51_Repeater"};
        respawnWeapons[] = {"OPTRE_FC_T51_Repeater"};

        magazines[] = {"OPTRE_FC_T51_Repeater_Battery","OPTRE_FC_T51_Repeater_Battery"};
        respawnMagazines[] = {"OPTRE_FC_T51_Repeater_Battery","OPTRE_FC_T51_Repeater_Battery"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T51_Repeater","","","",{"OPTRE_FC_T51_Repeater_Battery",400},{},""},{},{},{"OPTRE_FC_Elite_CombatSkin",{{"FirstAidKit",1},{"OPTRE_FC_T51_Repeater_Battery",3,400},{"OPTRE_FC_PlasmaGrenade",2,1}}},{"OPTRE_FC_Elite_Armor_Major",{}},{},"OPTRE_FC_Elite_Helmet_Major","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_FC_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Elite_Officer_WBK_01 : WBK_EliteMainWeap_6_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Elite Officer (WBK)";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"Elite03SNG"};

        uniformClass = "OPTRE_FC_Elite_CombatSkin";

        linkedItems[] = {"OPTRE_FC_Elite_Armor_Officer","OPTRE_FC_Elite_Helmet_Officer","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_FC_NVG"};
        respawnlinkedItems[] = {"OPTRE_FC_Elite_Armor_Officer","OPTRE_FC_Elite_Helmet_Officer","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_FC_NVG"};

        weapons[] = {"OPTRE_FC_T25_Rifle"};
        respawnWeapons[] = {"OPTRE_FC_T25_Rifle"};

        magazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_T25_Rifle_Battery"};
        respawnMagazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_T25_Rifle_Battery"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T25_Rifle","","","",{"OPTRE_FC_T25_Rifle_Battery",250},{},""},{},{},{"OPTRE_FC_Elite_CombatSkin",{{"FirstAidKit",1},{"OPTRE_FC_T25_Rifle_Battery",3,250},{"OPTRE_FC_PlasmaGrenade",1,1}}},{"OPTRE_FC_Elite_Armor_Officer",{}},{},"OPTRE_FC_Elite_Helmet_Officer","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_FC_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Hunter_01 : WBK_HaloHunter_2_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Hunter";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"empty_Face"};

        uniformClass = "Hunter_Uniform";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"Hunter_Uniform",{}},{},{},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Jackal_01 : OPTRE_Jackal_F_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Jackal";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"OPTRE_Jackal_03","OPTRE_Jackal_03"};

        uniformClass = "OPTRE_U_Jackal_uniform";

        linkedItems[] = {"OPTRE_V_Jackal_red_vest"};
        respawnlinkedItems[] = {"OPTRE_V_Jackal_red_vest"};

        weapons[] = {"OPTRE_FC_Jackal_Red_Shield"};
        respawnWeapons[] = {"OPTRE_FC_Jackal_Red_Shield"};

        magazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","OPTRE_FC_Plasma_Pistol_Battery"};
        respawnMagazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","OPTRE_FC_Plasma_Pistol_Battery"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_Jackal_Red_Shield","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{},{},{"OPTRE_U_Jackal_uniform",{{"OPTRE_FC_Plasma_Pistol_Battery",3,300}}},{"OPTRE_V_Jackal_red_vest",{}},{},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Jackal_Sniper_01 : OPTRE_Jackal_Sniper_F_IND_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Jackal Sniper";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"OPTRE_Jackal_03","OPTRE_Jackal_03"};

        uniformClass = "OPTRE_U_Jackal_uniform";

        linkedItems[] = {"OPTRE_V_Jackal_red_vest","OPTRE_FC_Jackal_T_Headgear","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_V_Jackal_red_vest","OPTRE_FC_Jackal_T_Headgear","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_FC_T50_SRS"};
        respawnWeapons[] = {"OPTRE_FC_T50_SRS"};

        magazines[] = {"OPTRE_FC_T50_SRS_Battery","OPTRE_FC_T50_SRS_Battery"};
        respawnMagazines[] = {"OPTRE_FC_T50_SRS_Battery","OPTRE_FC_T50_SRS_Battery"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T50_SRS","","","",{"OPTRE_FC_T50_SRS_Battery",10},{},""},{},{},{"OPTRE_U_Jackal_uniform",{{"OPTRE_NVG",1},{"OPTRE_FC_T50_SRS_Battery",3,10}}},{"OPTRE_V_Jackal_red_vest",{}},{},"OPTRE_FC_Jackal_T_Headgear","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Jackal_Marksman_01 : OPTRE_Jackal_Sharpshooter_F_IND_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Jackal Marksman";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"OPTRE_Jackal_03","OPTRE_Jackal_03"};

        uniformClass = "OPTRE_U_Jackal_uniform";

        linkedItems[] = {"OPTRE_V_Jackal_red_vest","OPTRE_FC_Jackal_T_Headgear","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_V_Jackal_red_vest","OPTRE_FC_Jackal_T_Headgear","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_FC_T51B_Carbine"};
        respawnWeapons[] = {"OPTRE_FC_T51B_Carbine"};

        magazines[] = {"OPTRE_FC_Blamite_Mag","OPTRE_FC_Blamite_Mag"};
        respawnMagazines[] = {"OPTRE_FC_Blamite_Mag","OPTRE_FC_Blamite_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T51B_Carbine","","","",{"OPTRE_FC_Blamite_Mag",21},{},""},{},{},{"OPTRE_U_Jackal_uniform",{{"OPTRE_NVG",1},{"OPTRE_FC_Blamite_Mag",3,21}}},{"OPTRE_V_Jackal_red_vest",{{"OPTRE_FC_Blamite_Mag",4,21}}},{},"OPTRE_FC_Jackal_T_Headgear","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Grunt_01 : WBK_Grunt_2_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Grunt";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"empty_Face"};

        uniformClass = "Grunt_Uniform";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"Grunt_Uniform",{}},{},{},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Wraith_01 : OPTRE_FC_Wraith_IND_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Wraith";
        side = 1;
        faction = "B_CovenantEmpire";
        crew = "B_Covenant_Empire_Crimson_Elite_Minor_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_Covenant_Empire_Crimson_Elite_Minor_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_body_co.paa'];_unit setObjectTextureGlobal [1,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_wings_co.paa'];_unit setObjectTextureGlobal [2,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_trail_co.paa'];_unit setObjectTextureGlobal [3,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_mortar_co.paa'];_unit setObjectTextureGlobal [4,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_cage_n_gunner_co.paa'];_unit setObjectTextureGlobal [5,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_smg_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Base";

    };

    class B_Covenant_Empire_Crimson_Sceptre_01 : OPTRE_FC_Spectre_AI_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Spectre (AI)";
        side = 1;
        faction = "B_CovenantEmpire";
        crew = "B_Covenant_Empire_Crimson_Elite_Minor_01";

        class Turrets : Turrets {
            class CargoTurret1 : CargoTurret1 { gunnerType = ""; };
            class CargoTurret2 : CargoTurret2 { gunnerType = ""; };
            class MainTurret : MainTurret { gunnerType = "B_Covenant_Empire_Crimson_Elite_Minor_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Spectre_AT_01 : OPTRE_FC_Spectre_AT_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Spectre (AT)";
        side = 1;
        faction = "B_CovenantEmpire";
        crew = "B_Covenant_Empire_Crimson_Elite_Minor_01";

        class Turrets : Turrets {
            class CargoTurret1 : CargoTurret1 { gunnerType = ""; };
            class CargoTurret2 : CargoTurret2 { gunnerType = ""; };
            class MainTurret : MainTurret { gunnerType = "B_Covenant_Empire_Crimson_Elite_Minor_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Banshee_01 : OPTRE_FC_Type27_Banshee_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Banshee";
        side = 1;
        faction = "B_CovenantEmpire";
        crew = "B_Covenant_Empire_Crimson_Elite_Minor_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Spirit_01 : OPTRE_FC_Spirit_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Spirit";
        side = 1;
        faction = "B_CovenantEmpire";
        crew = "B_Covenant_Empire_Crimson_Elite_Minor_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_Covenant_Empire_Crimson_Elite_Minor_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class CargoTurret_10 : CargoTurret_10 { gunnerType = ""; };
            class CargoTurret_11 : CargoTurret_11 { gunnerType = ""; };
            class CargoTurret_12 : CargoTurret_12 { gunnerType = ""; };
            class CargoTurret_13 : CargoTurret_13 { gunnerType = ""; };
            class CargoTurret_14 : CargoTurret_14 { gunnerType = ""; };
            class CargoTurret_15 : CargoTurret_15 { gunnerType = ""; };
            class CargoTurret_16 : CargoTurret_16 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Covenant_Empire_Crimson_Elite_Marksman_01 : OPTRE_FC_Elite_Major_OCimport_02 {
        author = "ENS. G. Shadow";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crimson Elite Marksman";
        side = 1;
        faction = "B_CovenantEmpire";

        identityTypes[] = {"Elite03SNG"};

        uniformClass = "OPTRE_FC_Elite_CombatSkin";

        linkedItems[] = {"OPTRE_FC_Elite_Armor_Major","OPTRE_FC_Elite_Helmet_Major","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_FC_Elite_Armor_Major","OPTRE_FC_Elite_Helmet_Major","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_FC_T51B_Carbine"};
        respawnWeapons[] = {"OPTRE_FC_T51B_Carbine"};

        magazines[] = {"OPTRE_FC_Blamite_Mag","OPTRE_FC_Blamite_Mag"};
        respawnMagazines[] = {"OPTRE_FC_Blamite_Mag","OPTRE_FC_Blamite_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T51B_Carbine","","","",{"OPTRE_FC_Blamite_Mag",21},{},""},{},{},{"OPTRE_FC_Elite_CombatSkin",{{"FirstAidKit",1},{"OPTRE_FC_NVG",1},{"OPTRE_FC_PlasmaGrenade",2,1},{"OPTRE_FC_Blamite_Mag",3,21}}},{"OPTRE_FC_Elite_Armor_Major",{{"OPTRE_FC_Blamite_Mag",7,21}}},{},"OPTRE_FC_Elite_Helmet_Major","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};