//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152405 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {
        class O_1ITA {
            name = "1st Independent Tank Army";

            class Infantry {
                name = "Infantry";

                class O_1ITA_infantry_squad {
                    name = "Squad";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_1ITA_SquadLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_1ITA_RadioOperator";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_1ITA_CombatMedic";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_Autorifleman";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_Rifleman";
                    };
                    class Unit5 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_Rifleman";
                    };
                    class Unit6 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_Rifleman";
                    };
                    class Unit7 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_AntiTankSpecialist";
                    };
                    class Unit8 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_Sniper";
                    };
                };

                class O_1ITA_infantry_team {
                    name = "Fireteam";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;
                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_1ITA_SquadLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_1ITA_Autorifleman";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_AntiTankSpecialist";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_Rifleman";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class o_1ITA_infantry_sof_squad {
                    name = "SOF Squad";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_1ITA_SquadLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_1ITA_Officer";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_1ITA_Heavy_Gunner";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_1ITA_Heavy_Gunner";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_AntiTankSpecialist";
                    };
                };

                class O_1ITA_SOF_Heavy_Team {
                    name = "Heavy Weapons Team";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;
                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CAPTAIN";
                        side = 0;
                        vehicle = "O_1ITA_Heavy_Gunner";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_1ITA_Heavy_Gunner";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_1ITA_Heavy_Gunner";
                    };
                };

            };

            class Motorized {
                name = "Motorized";

                class o_1ITA_m413_hunter_squad {
                    name = "M413 Hunter Squad";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "BDA_1ITA_M413_MGS";
                    };
                    class Unit1 {
                        position[] = {6,-15,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "BDA_1ITA_M413_MGS";
                    };
                };

                class o_1ITA_m412_bison_patrol {
                    name = "M412 Bison Patrol";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "BDA_1ITA_M412_IFV";
                    };
                    class Unit1 {
                        position[] = {6,-15,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "BDA_1ITA_M412_IFV";
                    };
                };

            };

            class Support {
                name = "Support Infantry";

                class o_1ITA_support_support_squad {
                    name = "Support Squad";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_1ITA_SquadLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_RadioOperator";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_CombatCrewman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_CombatCrewman";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_1ITA_CombatCrewman";
                    };
                };

                class o_1ITA_support_helicopter_crew {
                    name = "Helicopter Crew";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_1ITA_Heli_Pilot";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_1ITA_Heli_Pilot";
                    };
                };

                class O_1ITA_Support_Sniper_Team {
                    name = "Sniper Team";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;
                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_1ITA_Sniper";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_1ITA_Rifleman";
                    };
                };

                
            };

            class Mechanized {
                name = "Mechanized Infantry";
            };

            class Armored {
                name = "Armored";

                class o_1ITA_t1000x_platoon {
                    name = "T-1000X Platoon";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CAPTAIN";
                        side = 0;
                        vehicle = "BDA_1ITA_T1000X";
                    };
                    class Unit1 {
                        position[] = {10,-16,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "BDA_1ITA_T1000X";
                    };
                    class Unit2 {
                        position[] = {-10,-16,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "BDA_1ITA_T1000X";
                    };
                };

            };

            class Artillery {
                name = "Artillery";
            };

            class Naval {
                name = "Naval";
            };

            class Air {
                name = "Air";

                class o_1ITA_m480_squadron {
                    name = "M480 Super Alligator Squadron";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "COLONEL";
                        side = 0;
                        vehicle = "BDA_1ITA_Kaijman_Dynamic";
                    };
                    class Unit1 {
                        position[] = {22,-26,0};
                        rank = "CAPTAIN";
                        side = 0;
                        vehicle = "BDA_1ITA_Kaijman_Dynamic";
                    };
                };

                class o_1ITA_m214_wing {
                    name = "M214 Shikra Wing";
                    side = 0;
                    faction = "O_1ITA";
                    icon = "\A3\ui_f\data\map\markers\nato\o_plane.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "COLONEL";
                        side = 0;
                        vehicle = "BDA_1ITA_Shikra";
                    };
                    class Unit1 {
                        position[] = {23,-33,0};
                        rank = "MAJOR";
                        side = 0;
                        vehicle = "BDA_1ITA_Shikra";
                    };
                };

            };

        };

    };
};
