//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152405 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_SL_F;
    class O_Soldier_SL_F_OCimport_01 : O_Soldier_SL_F { scope = 0; class EventHandlers; };
    class O_Soldier_SL_F_OCimport_02 : O_Soldier_SL_F_OCimport_01 { class EventHandlers; };


    class O_1ITA_SquadLeader : O_Soldier_SL_F_OCimport_02 {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","Rogue_CECapGrey","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","Rogue_CECapGrey","OPTRE_NVG"};

        weapons[] = {"TCF_ARMX","TCF_M2311_D"};
        respawnWeapons[] = {"TCF_ARMX","TCF_M2311_D"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Rogue_CEBackpack";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARMX","","","optic_Arco_blk_F",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_32Rnd_762x51_Mag",6,32},{"OPTRE_16Rnd_127x40_Black_Mag",2,16}}},{"Rogue_CEBackpack",{}},"Rogue_CECapGrey","G_Bandanna_blk",{},{"","","","","","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_Sniper : O_1ITA_SquadLeader {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","Rogue_CEBoonieGrey"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","Rogue_CEBoonieGrey"};

        weapons[] = {"srifle_LRR_F","TCF_M2311_D"};
        respawnWeapons[] = {"srifle_LRR_F","TCF_M2311_D"};

        magazines[] = {"7Rnd_408_Mag","OPTRE_8Rnd_127x40_Mag","7Rnd_408_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"7Rnd_408_Mag","OPTRE_8Rnd_127x40_Mag","7Rnd_408_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Rogue_CEBackpackScout";

        ALiVE_orbatCreator_loadout[] = {{"srifle_LRR_F","","","optic_AMS",{"7Rnd_408_Mag",7},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_16Rnd_127x40_Black_Mag",2,16},{"ACE_7Rnd_408_305gr_Mag",3,7}}},{"Rogue_CEBackpackScout",{}},"Rogue_CEBoonieGrey","TCF_Eyepiece",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_RadioOperator : O_1ITA_SquadLeader {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Radio Operator";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","Rogue_CECapGrey","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","Rogue_CECapGrey","OPTRE_NVGT_C"};

        weapons[] = {"OPTRE_M6D_Carbine_Black_F"};
        respawnWeapons[] = {"OPTRE_M6D_Carbine_Black_F"};

        magazines[] = {"OPTRE_26Rnd_127x40_Mag_Black_Tracer","OPTRE_26Rnd_127x40_Mag_Black_Tracer"};
        respawnMagazines[] = {"OPTRE_26Rnd_127x40_Mag_Black_Tracer","OPTRE_26Rnd_127x40_Mag_Black_Tracer"};

        backpack = "19thMD_Backpack_Standard_rto";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M6D_Carbine_Black_F","OPTRE_M6D_Carbine_Suppressor","OPTRE_M6D_Carbine_IR","Optre_Recon_Sight",{"OPTRE_26Rnd_127x40_Mag_Black_Tracer",26},{},""},{},{},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_26Rnd_127x40_Mag_Black_Tracer",4,26},{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1}}},{"19thMD_Backpack_Standard_rto",{}},"Rogue_CECapGrey","G_Bandanna_blk",{},{"","","","","","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_Rifleman : O_1ITA_RadioOperator {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","OPTRE_FC_CH255_Helmet_URB","OPTRE_NVG_HURS_HUL"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","OPTRE_FC_CH255_Helmet_URB","OPTRE_NVG_HURS_HUL"};

        weapons[] = {"TCF_ARMX","TCF_M2311_D"};
        respawnWeapons[] = {"TCF_ARMX","TCF_M2311_D"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Rogue_CEBackpackScout";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARMX","","","optic_Hamr",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_16Rnd_127x40_Black_Mag",2,16}}},{"Rogue_CEBackpackScout",{}},"OPTRE_FC_CH255_Helmet_URB","",{},{"","","","","","OPTRE_NVG_HURS_HUL"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_Officer : O_1ITA_SquadLeader {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","Rogue_CECapGrey","OPTRE_NVGT_C"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","Rogue_CECapGrey","OPTRE_NVGT_C"};

        weapons[] = {"OPTRE_M6D_Carbine_Black_F"};
        respawnWeapons[] = {"OPTRE_M6D_Carbine_Black_F"};

        magazines[] = {"OPTRE_26Rnd_127x40_Mag_Black_Tracer","OPTRE_26Rnd_127x40_Mag_Black_Tracer"};
        respawnMagazines[] = {"OPTRE_26Rnd_127x40_Mag_Black_Tracer","OPTRE_26Rnd_127x40_Mag_Black_Tracer"};

        backpack = "Rogue_CEBackpack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M6D_Carbine_Black_F","OPTRE_M6D_Carbine_Brake","OPTRE_M6D_Carbine_Vis_Red","Optre_Recon_Sight",{"OPTRE_26Rnd_127x40_Mag_Black_Tracer",26},{},""},{},{},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_26Rnd_127x40_Mag_Black_Tracer",4,26},{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1}}},{"Rogue_CEBackpack",{}},"Rogue_CECapGrey","G_Bandanna_blk",{},{"","","","","","OPTRE_NVGT_C"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_Heavy_Gunner : O_1ITA_Rifleman {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy Gunner";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_CGAVest_Bwn","TCF_TH56","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_CGAVest_Bwn","TCF_TH56","OPTRE_NVG"};

        weapons[] = {"OPTRE_M247H_Shield_Etilka","TCF_M2311_D"};
        respawnWeapons[] = {"OPTRE_M247H_Shield_Etilka","TCF_M2311_D"};

        magazines[] = {"OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_8Rnd_127x40_Mag","OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_8Rnd_127x40_Mag","OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_8Rnd_127x40_Mag"};

        backpack = "TCF_RUCKSACK_UNSC_URB_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M247H_Shield_Etilka","","","",{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",200},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_CGAVest_Bwn",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},{"TCF_RUCKSACK_UNSC_URB_F",{{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",2,200}}},"TCF_TH56","TCF_Eyepiece",{},{"","","","","","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_Autorifleman : O_1ITA_Rifleman {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","OPTRE_FC_CH255_Helmet_URB","OPTRE_NVG_UL_HUL"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","OPTRE_FC_CH255_Helmet_URB","OPTRE_NVG_UL_HUL"};

        weapons[] = {"TCF_CM_12_Insurgent","TCF_M2311_D"};
        respawnWeapons[] = {"TCF_CM_12_Insurgent","TCF_M2311_D"};

        magazines[] = {"TCF_150Rnd_30x06_Mag","OPTRE_8Rnd_127x40_Mag","TCF_150Rnd_30x06_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"TCF_150Rnd_30x06_Mag","OPTRE_8Rnd_127x40_Mag","TCF_150Rnd_30x06_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"TCF_CM_12_Insurgent","","","OPTRE_BR45_Scope",{"TCF_150Rnd_30x06_Mag",150},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_16Rnd_127x40_Black_Mag",2,16}}},{"OPTRE_UNSC_Backpack",{{"TCF_150Rnd_30x06_Mag",5,150}}},"OPTRE_FC_CH255_Helmet_URB","TCF_URB_UP_Shemagheye",{},{"","","","","","OPTRE_NVG_UL_HUL"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_AntiTankSpecialist : O_1ITA_Rifleman {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Anti-Tank Specialist";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","OPTRE_FC_CH255_Helmet_URB","OPTRE_NVG_UL_HUL"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","OPTRE_FC_CH255_Helmet_URB","OPTRE_NVG_UL_HUL"};

        weapons[] = {"TCF_ARMX","TCF_M30DFLSF","TCF_M2311_D"};
        respawnWeapons[] = {"TCF_ARMX","TCF_M30DFLSF","TCF_M2311_D"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","TCF_1Rnd_50x137_THERMO","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","TCF_1Rnd_50x137_THERMO","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Rogue_CEBackpack";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARMX","","","optic_Holosight_blk_F",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"TCF_M30DFLSF","","","",{"TCF_1Rnd_50x137_THERMO",1},{},""},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_16Rnd_127x40_Black_Mag",2,16}}},{"Rogue_CEBackpack",{{"TCF_1Rnd_50x137_THERMO",2,1},{"TCF_1Rnd_50x137_PEN",2,1},{"TCF_1Rnd_50x137_HEAT",2,1}}},"OPTRE_FC_CH255_Helmet_URB","TCF_Eyepiece",{},{"","","","","","OPTRE_NVG_UL_HUL"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_CombatMedic : O_1ITA_Rifleman {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Combat Medic";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "TCF_SU2_Uni";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","Rogue_CECapGrey","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","Rogue_CECapGrey","OPTRE_NVG"};

        weapons[] = {"OPTRE_M6D_Carbine_Black_F"};
        respawnWeapons[] = {"OPTRE_M6D_Carbine_Black_F"};

        magazines[] = {"OPTRE_26Rnd_127x40_Mag_Black_Tracer","OPTRE_26Rnd_127x40_Mag_Black_Tracer"};
        respawnMagazines[] = {"OPTRE_26Rnd_127x40_Mag_Black_Tracer","OPTRE_26Rnd_127x40_Mag_Black_Tracer"};

        backpack = "19thMD_Backpack_Standard_Med";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M6D_Carbine_Black_F","OPTRE_M6D_Carbine_Brake","OPTRE_M6D_Carbine_Flashlight","Optre_Recon_Sight",{"OPTRE_26Rnd_127x40_Mag_Black_Tracer",26},{},""},{},{},{"TCF_SU2_Uni",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_26Rnd_127x40_Mag_Black_Tracer",5,26},{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1}}},{"19thMD_Backpack_Standard_Med",{{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_quikclot",15},{"ACE_packingBandage",15},{"ACE_elasticBandage",15},{"ACE_fieldDressing",15},{"ACE_bloodIV",2},{"ACE_bloodIV_250",4},{"ACE_bloodIV_500",4},{"ACE_salineIV_500",2},{"ACE_salineIV_250",2},{"ACE_plasmaIV_500",1},{"ACE_surgicalKit",1},{"ACE_splint",6},{"OPTRE_Biofoam",8},{"ACE_tourniquet",8}}},"Rogue_CECapGrey","G_Bandanna_blk",{},{"","","","","","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_CombatCrewman : O_1ITA_Rifleman {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Combat Crewman";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","TCF_SU_Sniper","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","TCF_SU_Sniper","OPTRE_NVG"};

        weapons[] = {"TCF_ARMX","TCF_M2311_D"};
        respawnWeapons[] = {"TCF_ARMX","TCF_M2311_D"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Rogue_CEBackpack";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ARMX","","","TCF_REC_holo",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"TCF_M2311_D","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_32Rnd_762x51_Mag",6,32},{"OPTRE_16Rnd_127x40_Black_Mag",2,16}}},{"Rogue_CEBackpack",{}},"TCF_SU_Sniper","TCF_Eyepiece",{},{"","","","","","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_Heli_Pilot : O_1ITA_Officer {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heli Pilot";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","DMNS_IHADSS_HELMET_01","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","DMNS_IHADSS_HELMET_01","OPTRE_NVG"};

        weapons[] = {"OPTRE_M6D_Carbine_Black_F"};
        respawnWeapons[] = {"OPTRE_M6D_Carbine_Black_F"};

        magazines[] = {"OPTRE_26Rnd_127x40_Mag_Black_Tracer","OPTRE_26Rnd_127x40_Mag_Black_Tracer"};
        respawnMagazines[] = {"OPTRE_26Rnd_127x40_Mag_Black_Tracer","OPTRE_26Rnd_127x40_Mag_Black_Tracer"};

        backpack = "Rogue_CEBackpackLR";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M6D_Carbine_Black_F","","","",{"OPTRE_26Rnd_127x40_Mag_Black_Tracer",26},{},""},{},{},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_26Rnd_127x40_Mag_Black_Tracer",4,26},{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1}}},{"Rogue_CEBackpackLR",{}},"DMNS_IHADSS_HELMET_01","G_Bandanna_blk",{},{"","","","","","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_JetPilot : O_1ITA_Heli_Pilot {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Jet Pilot";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"TCF_M52A_MC_Light_CEA_U","DMNS_IHADSS_HELMET_01","OPTRE_NVG"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Light_CEA_U","DMNS_IHADSS_HELMET_01","OPTRE_NVG"};

        weapons[] = {"OPTRE_M6D_Carbine_Black_F"};
        respawnWeapons[] = {"OPTRE_M6D_Carbine_Black_F"};

        magazines[] = {"OPTRE_26Rnd_127x40_Mag_Black_Tracer","OPTRE_26Rnd_127x40_Mag_Black_Tracer"};
        respawnMagazines[] = {"OPTRE_26Rnd_127x40_Mag_Black_Tracer","OPTRE_26Rnd_127x40_Mag_Black_Tracer"};

        backpack = "Rogue_CEBackpackLR";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M6D_Carbine_Black_F","","","",{"OPTRE_26Rnd_127x40_Mag_Black_Tracer",26},{},""},{},{},{"Rogue_CEUniform_U_B",{{"ACE_elasticBandage",5},{"ACE_quikclot",5},{"ACE_tourniquet",1},{"ACE_splint",1},{"ACE_painkillers",1,10}}},{"TCF_M52A_MC_Light_CEA_U",{{"OPTRE_26Rnd_127x40_Mag_Black_Tracer",4,26},{"OPTRE_M9_Frag",1,1},{"OPTRE_M2_Smoke",2,1}}},{"Rogue_CEBackpackLR",{}},"DMNS_IHADSS_HELMET_01","G_Bandanna_blk",{},{"","","","","","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_General_Jeremiah_Bryers : O_1ITA_Officer {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "General Jeremiah Bryers";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";
        editorSubCategory = "1ITA_ESC_Story";

        identityTypes[] = {"Head_Greek","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_B_ParadeUniform_01_US_F";

        linkedItems[] = {"H_ParadeDressCap_01_US_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_ParadeDressCap_01_US_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_B_ParadeUniform_01_US_F",{}},{},{},"H_ParadeDressCap_01_US_F","immersion_cigs_cigar0",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_Colonel_Erin_Arnessen : O_1ITA_Officer {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Colonel Erin Arnessen";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";
        editorSubCategory = "1ITA_ESC_Story";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_I_E_ParadeUniform_01_LDF_F";

        linkedItems[] = {"H_ParadeDressCap_01_LDF_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_ParadeDressCap_01_LDF_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_I_E_ParadeUniform_01_LDF_F",{}},{},{},"H_ParadeDressCap_01_LDF_F","murshun_cigs_cig0",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_Emile_Higgs : O_1ITA_Officer {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Emile Higgs";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";
        editorSubCategory = "1ITA_ESC_Story";

        identityTypes[] = {"Head_Greek","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_ONI_Researcher_Uniform";

        linkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"OPTRE_ONI_Researcher_Uniform",{}},{},{},"","G_Spectacles",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_Michael_Summers : O_1ITA_Officer {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Michael Summers";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";
        editorSubCategory = "1ITA_ESC_Story";

        identityTypes[] = {"Head_Greek","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_ONI_Researcher_Uniform_Light";

        linkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"OPTRE_ONI_Researcher_Uniform_Light",{}},{},{},"","G_Spectacles",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_TSG_Joto_Isakari : O_1ITA_Officer {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "TSG Joto Isakari";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";
        editorSubCategory = "1ITA_ESC_Story";

        identityTypes[] = {"Head_Asian","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_C_Driver_1_black";

        linkedItems[] = {"TCF_M52A_MC_Vest_CEA_U","OPTRE_CPD_Beret","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"TCF_M52A_MC_Vest_CEA_U","OPTRE_CPD_Beret","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_Driver_1_black",{}},{"TCF_M52A_MC_Vest_CEA_U",{}},{},"OPTRE_CPD_Beret","G_Spectacles",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_1ITA_Michael_Kargrove : O_1ITA_Officer {
        author = "1stLt. R. Ribbington";
        scope = 2;
        scopeCurator = 2;
        displayName = "Michael Kargrove";
        side = 0;
        faction = "O_1ITA";
		editorCategory = "BDA_EC_1ITA";
        editorSubCategory = "1ITA_ESC_Story";

        identityTypes[] = {"Head_NATO","LanguagePER_F","G_IRAN_default"};

        uniformClass = "Rogue_CEUniform_U_B";

        linkedItems[] = {"Rogue_CEArmourScout","VES_Beret_MP","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"Rogue_CEArmourScout","VES_Beret_MP","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"Rogue_CEUniform_U_B",{}},{"Rogue_CEArmourScout",{}},{},"VES_Beret_MP","OPTRE_HUD_g_Glasses",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};